import type { CalculatorConfig } from '../../types';

export const match401kCalculator: CalculatorConfig = {
  id: '401k-match',
  title: '401(k) Employer Match Optimizer',
  description: 'Maximize 401(k) employer match and optimize contribution strategy',
  category: 'personal',
  icon: '💼',
  color: 'blue',
  keywords: ['401k', 'employer match', 'retirement', 'contribution'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How does 401(k) employer matching work?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: "Employer matching means your employer contributes money to your 401(k) based on your contributions. For example, if your employer matches 50% up to 6% of salary, contributing 6% gets you an additional 3% from your employer - that's free money!",
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Personal Finance', href: '/models/personal' },
    { name: '401(k) Match Optimizer', href: '/calculator/401k-match' },
  ],
  formFields: [
    {
      id: 'employerMatch',
      name: 'employerMatch',
      type: 'number',
      label: 'Employer Match (%)',
      min: 0,
      max: 100,
      step: 0.01,
      required: true,
      group: 'Plan Details',
    },
    {
      id: 'matchLimit',
      name: 'matchLimit',
      type: 'number',
      label: 'Match Limit (% of salary)',
      min: 0,
      max: 100,
      step: 0.01,
      required: true,
      group: 'Plan Details',
    },
    {
      id: 'vestingSchedule',
      name: 'vestingSchedule',
      type: 'select',
      label: 'Vesting Schedule',
      required: true,
      group: 'Plan Details',
      options: [
        { value: 'immediate', label: 'Immediate' },
        { value: 'cliff', label: 'Cliff' },
        { value: 'graded', label: 'Graded' },
      ],
    },
    {
      id: 'annualSalary',
      name: 'annualSalary',
      type: 'number',
      label: 'Annual Salary ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Employee Info',
    },
    {
      id: 'currentContribution',
      name: 'currentContribution',
      type: 'number',
      label: 'Current Contribution (% of salary)',
      min: 0,
      max: 50,
      step: 0.01,
      required: true,
      group: 'Employee Info',
    },
  ],
  clientScript: '401k-match',
  analysisType: '401k-match',
};
