import type { CalculatorConfig } from '../../types';

export const credit_card_payoffCalculator: CalculatorConfig = {
  id: 'credit-card-payoff',
  title: 'Credit Card Payoff Calculator',
  description:
    'Optimize credit card debt payoff with balance transfer analysis, utilization impact, and escape the minimum payment trap',
  category: 'personal',
  icon: '💳',
  color: 'red',
  keywords: ['credit card', 'debt', 'payoff', 'balance transfer', '0% APR', 'utilization'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'Should I do a balance transfer?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Balance transfers to 0% APR cards can save thousands in interest if you pay off the balance during the promotional period. Watch out for transfer fees (typically 3-5%) and ensure you can pay it off before the promo ends.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Models', href: '/models' },
    { name: 'Credit Card Payoff', href: '/calculator/credit-card-payoff' },
  ],
  formFields: [
    {
      id: 'balance',
      name: 'balance',
      type: 'number',
      label: 'Card Balance ($)',
      min: 0,
      step: 50,
      required: true,
      placeholder: '5000',
      group: '💳 Current Card',
    },
    {
      id: 'interestRate',
      name: 'interestRate',
      type: 'number',
      label: 'Interest Rate (% APR)',
      min: 0,
      max: 35,
      step: 0.1,
      required: true,
      placeholder: '18.99',
      group: '💳 Current Card',
    },
    {
      id: 'creditLimit',
      name: 'creditLimit',
      type: 'number',
      label: 'Credit Limit ($)',
      min: 0,
      step: 100,
      required: true,
      placeholder: '10000',
      group: '💳 Current Card',
      helpText: 'For utilization calculation',
    },
    {
      id: 'minimumPaymentPercent',
      name: 'minimumPaymentPercent',
      type: 'number',
      label: 'Minimum Payment (%)',
      min: 1,
      max: 10,
      step: 0.1,
      placeholder: '2',
      group: '💳 Current Card',
      helpText: 'Typically 2-3% of balance',
    },
    {
      id: 'monthlyPayment',
      name: 'monthlyPayment',
      type: 'number',
      label: 'Your Monthly Payment ($)',
      min: 0,
      step: 25,
      required: true,
      placeholder: '200',
      group: '💰 Payoff Plan',
    },
    {
      id: 'balanceTransferOffer',
      name: 'balanceTransferOffer',
      type: 'select',
      label: 'Balance Transfer Offer Available?',
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
      ],
      group: '🔄 Balance Transfer (Optional)',
    },
    {
      id: 'transferAPR',
      name: 'transferAPR',
      type: 'number',
      label: 'Transfer Promo APR (%)',
      min: 0,
      max: 10,
      step: 0.1,
      placeholder: '0',
      group: '🔄 Balance Transfer (Optional)',
      helpText: 'Often 0% for intro period',
    },
    {
      id: 'transferFee',
      name: 'transferFee',
      type: 'number',
      label: 'Transfer Fee (%)',
      min: 0,
      max: 10,
      step: 0.1,
      placeholder: '3',
      group: '🔄 Balance Transfer (Optional)',
      helpText: 'Typically 3-5% of balance',
    },
    {
      id: 'transferPromoPeriod',
      name: 'transferPromoPeriod',
      type: 'select',
      label: 'Promo Period (months)',
      options: [
        { value: '6', label: '6 months' },
        { value: '12', label: '12 months' },
        { value: '15', label: '15 months' },
        { value: '18', label: '18 months' },
        { value: '21', label: '21 months' },
      ],
      group: '🔄 Balance Transfer (Optional)',
    },
  ],
  clientScript: 'credit-card-payoff',
  analysisType: 'credit-card-payoff',
};
