import type { CalculatorConfig } from '../../types';

export const emergency_fundCalculator: CalculatorConfig = {
  id: 'emergency-fund',
  title: 'Emergency Fund Calculator',
  description: 'Calculate emergency fund target, build timeline, and withdrawal scenarios',
  category: 'personal',
  icon: '🆘',
  color: 'red',
  keywords: ['emergency fund', 'savings', 'financial security'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How much should I have in my emergency fund?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Most experts recommend 3-6 months of expenses in an emergency fund. Self-employed individuals or those with irregular income should aim for 6-12 months.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Personal Finance', href: '/models/personal' },
    { name: 'Emergency Fund Calculator', href: '/calculator/emergency-fund' },
  ],
  formFields: [
    {
      id: 'monthlyExpenses',
      name: 'monthlyExpenses',
      type: 'number',
      label: 'Monthly Expenses ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Current Situation',
    },
    {
      id: 'monthlyIncome',
      name: 'monthlyIncome',
      type: 'number',
      label: 'Monthly Income ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Current Situation',
    },
    {
      id: 'currentEmergencyFund',
      name: 'currentEmergencyFund',
      type: 'number',
      label: 'Current Emergency Fund ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Current Situation',
    },
    {
      id: 'dependents',
      name: 'dependents',
      type: 'number',
      label: 'Number of Dependents',
      min: 0,
      max: 10,
      required: true,
      group: 'Current Situation',
    },
    {
      id: 'employmentStatus',
      name: 'employmentStatus',
      type: 'select',
      label: 'Employment Status',
      required: true,
      group: 'Current Situation',
      options: [
        { value: 'employed', label: 'Employed' },
        { value: 'self-employed', label: 'Self-Employed' },
        { value: 'unemployed', label: 'Unemployed' },
        { value: 'retired', label: 'Retired' },
      ],
    },
    {
      id: 'targetMonths',
      name: 'targetMonths',
      type: 'number',
      label: 'Target Months of Expenses',
      min: 1,
      max: 24,
      required: true,
      group: 'Goals',
    },
    {
      id: 'monthlySavings',
      name: 'monthlySavings',
      type: 'number',
      label: 'Monthly Savings ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Assumptions',
    },
  ],
  clientScript: 'emergency-fund',
  analysisType: 'emergency-fund',
};
