import type { CalculatorConfig } from '../../types';

export const estate_planningCalculator: CalculatorConfig = {
  id: 'estate-planning',
  title: 'Estate Planning Calculator',
  description: 'Estate tax planning, inheritance projections, and trust analysis',
  category: 'personal',
  icon: '📜',
  color: 'purple',
  keywords: ['estate planning', 'estate tax', 'inheritance', 'trust'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is estate tax?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Estate tax is a tax on the transfer of property after death. The federal estate tax exemption is $12.92 million for 2024, but some states also have estate taxes with lower exemptions.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Personal Finance', href: '/models/personal' },
    { name: 'Estate Planning', href: '/calculator/estate-planning' },
  ],
  formFields: [
    {
      id: 'age',
      name: 'age',
      type: 'number',
      label: 'Age',
      min: 18,
      max: 100,
      required: true,
      group: 'Personal Information',
    },
    {
      id: 'maritalStatus',
      name: 'maritalStatus',
      type: 'select',
      label: 'Marital Status',
      required: true,
      group: 'Personal Information',
      options: [
        { value: 'single', label: 'Single' },
        { value: 'married', label: 'Married' },
        { value: 'divorced', label: 'Divorced' },
        { value: 'widowed', label: 'Widowed' },
      ],
    },
    {
      id: 'totalAssets',
      name: 'totalAssets',
      type: 'number',
      label: 'Total Assets ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Assets',
    },
    {
      id: 'realEstate',
      name: 'realEstate',
      type: 'number',
      label: 'Real Estate ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Assets',
    },
    {
      id: 'investments',
      name: 'investments',
      type: 'number',
      label: 'Investments ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Assets',
    },
    {
      id: 'retirementAccounts',
      name: 'retirementAccounts',
      type: 'number',
      label: 'Retirement Accounts ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Assets',
    },
    { id: 'hasWill', name: 'hasWill', type: 'checkbox', label: 'Has Will', group: 'Estate Plan' },
    {
      id: 'hasTrust',
      name: 'hasTrust',
      type: 'checkbox',
      label: 'Has Trust',
      group: 'Estate Plan',
    },
    {
      id: 'beneficiaries',
      name: 'beneficiaries',
      type: 'number',
      label: 'Number of Beneficiaries',
      min: 0,
      max: 20,
      required: true,
      group: 'Estate Plan',
    },
  ],
  clientScript: 'estate-planning',
  analysisType: 'estate-planning',
};
