import type { CalculatorConfig } from '../../types';

export const fire_calculatorCalculator: CalculatorConfig = {
  id: 'fire-calculator',
  title: 'FIRE Calculator',
  description:
    'Calculate Financial Independence (FIRE) number, retirement date, and savings strategies',
  category: 'personal',
  icon: '🔥',
  color: 'orange',
  keywords: ['fire', 'financial independence', 'retire early', 'coast fire', 'barista fire'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is FIRE?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: "FIRE stands for Financial Independence, Retire Early. It's a movement focused on extreme savings and investment to retire much earlier than traditional retirement age.",
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Personal Finance', href: '/models/personal' },
    { name: 'FIRE Calculator', href: '/calculator/fire-calculator' },
  ],
  formFields: [
    {
      id: 'age',
      name: 'age',
      type: 'number',
      label: 'Current Age',
      min: 18,
      max: 100,
      required: true,
      group: 'Current Situation',
    },
    {
      id: 'currentSavings',
      name: 'currentSavings',
      type: 'number',
      label: 'Current Savings ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Current Situation',
    },
    {
      id: 'annualIncome',
      name: 'annualIncome',
      type: 'number',
      label: 'Annual Income ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Current Situation',
    },
    {
      id: 'annualExpenses',
      name: 'annualExpenses',
      type: 'number',
      label: 'Annual Expenses ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Current Situation',
    },
    {
      id: 'monthlySavings',
      name: 'monthlySavings',
      type: 'number',
      label: 'Monthly Savings ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Current Situation',
    },
    {
      id: 'targetAge',
      name: 'targetAge',
      type: 'number',
      label: 'Target Retirement Age',
      min: 18,
      max: 100,
      required: true,
      group: 'FIRE Goals',
    },
    {
      id: 'annualExpensesInRetirement',
      name: 'annualExpensesInRetirement',
      type: 'number',
      label: 'Annual Expenses in Retirement ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'FIRE Goals',
    },
    {
      id: 'safeWithdrawalRate',
      name: 'safeWithdrawalRate',
      type: 'number',
      label: 'Safe Withdrawal Rate (%)',
      min: 2,
      max: 6,
      step: 0.1,
      required: true,
      group: 'FIRE Goals',
    },
    {
      id: 'expectedReturn',
      name: 'expectedReturn',
      type: 'number',
      label: 'Expected Return (%)',
      min: 0,
      max: 20,
      step: 0.01,
      required: true,
      group: 'Assumptions',
    },
  ],
  clientScript: 'fire-calculator',
  analysisType: 'fire-calculator',
};
