import type { CalculatorConfig } from '../../types';

export const helocCalculator: CalculatorConfig = {
  id: 'heloc',
  title: 'HELOC Analyzer',
  description:
    'Analyze Home Equity Line of Credit options and compare to refinancing and personal loans',
  category: 'personal',
  icon: '🏡',
  color: 'green',
  keywords: ['heloc', 'home equity', 'line of credit', 'refinancing'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is a HELOC?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'A Home Equity Line of Credit (HELOC) is a revolving line of credit secured by your home equity. You can borrow against it as needed during the draw period, then repay during the repayment period.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Personal Finance', href: '/models/personal' },
    { name: 'HELOC Analyzer', href: '/calculator/heloc' },
  ],
  formFields: [
    {
      id: 'currentHomeValue',
      name: 'currentHomeValue',
      type: 'number',
      label: 'Current Home Value ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Property Information',
    },
    {
      id: 'currentMortgageBalance',
      name: 'currentMortgageBalance',
      type: 'number',
      label: 'Current Mortgage Balance ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Property Information',
    },
    {
      id: 'mortgageInterestRate',
      name: 'mortgageInterestRate',
      type: 'number',
      label: 'Mortgage Interest Rate (%)',
      min: 0,
      max: 20,
      step: 0.01,
      required: true,
      group: 'Property Information',
    },
    {
      id: 'yearsRemaining',
      name: 'yearsRemaining',
      type: 'number',
      label: 'Years Remaining',
      min: 0,
      max: 30,
      required: true,
      group: 'Property Information',
    },
    {
      id: 'creditLimit',
      name: 'creditLimit',
      type: 'number',
      label: 'HELOC Credit Limit ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'HELOC Details',
    },
    {
      id: 'interestRate',
      name: 'interestRate',
      type: 'number',
      label: 'HELOC Interest Rate (%)',
      min: 0,
      max: 20,
      step: 0.01,
      required: true,
      group: 'HELOC Details',
    },
    {
      id: 'drawPeriod',
      name: 'drawPeriod',
      type: 'number',
      label: 'Draw Period (years)',
      min: 1,
      max: 10,
      required: true,
      group: 'HELOC Details',
    },
    {
      id: 'repaymentPeriod',
      name: 'repaymentPeriod',
      type: 'number',
      label: 'Repayment Period (years)',
      min: 1,
      max: 20,
      required: true,
      group: 'HELOC Details',
    },
    {
      id: 'drawAmount',
      name: 'drawAmount',
      type: 'number',
      label: 'Draw Amount ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Usage',
    },
    {
      id: 'purpose',
      name: 'purpose',
      type: 'select',
      label: 'Purpose',
      required: true,
      group: 'Usage',
      options: [
        { value: 'home-improvement', label: 'Home Improvement' },
        { value: 'debt-consolidation', label: 'Debt Consolidation' },
        { value: 'investment', label: 'Investment' },
        { value: 'education', label: 'Education' },
        { value: 'other', label: 'Other' },
      ],
    },
  ],
  clientScript: 'heloc',
  analysisType: 'heloc',
};
