import type { CalculatorConfig } from '../../types';

export const invest_vs_payoff_debtCalculator: CalculatorConfig = {
  id: 'invest-vs-payoff-debt',
  title: 'Invest vs Pay Off Debt Calculator',
  description:
    'Should you use extra money to pay off debt or invest it? Compare strategies with guaranteed vs expected returns',
  category: 'personal',
  icon: '⚖️',
  color: 'purple',
  keywords: ['invest', 'debt', 'payoff', 'investment', 'strategy', 'financial decision'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'Should I invest or pay off debt?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'If your debt interest rate is higher than expected investment returns (typically 7-10%), pay off debt first for a guaranteed return. If debt interest is low (<4%) and you have employer match, invest to capture free money.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Models', href: '/models' },
    { name: 'Invest vs Pay Debt', href: '/calculator/invest-vs-payoff-debt' },
  ],
  formFields: [
    {
      id: 'extraMoney',
      name: 'extraMoney',
      type: 'number',
      label: 'Extra Money Per Month ($)',
      min: 0,
      step: 50,
      required: true,
      placeholder: '500',
      group: '💰 Available Funds',
      helpText: 'How much extra can you put toward debt or investing?',
    },
    {
      id: 'debtBalance',
      name: 'debtBalance',
      type: 'number',
      label: 'Total Debt Balance ($)',
      min: 0,
      step: 100,
      required: true,
      placeholder: '10000',
      group: '💳 Debt Details',
    },
    {
      id: 'debtInterestRate',
      name: 'debtInterestRate',
      type: 'number',
      label: 'Debt Interest Rate (%)',
      min: 0,
      max: 30,
      step: 0.1,
      required: true,
      placeholder: '18',
      group: '💳 Debt Details',
    },
    {
      id: 'debtMinimumPayment',
      name: 'debtMinimumPayment',
      type: 'number',
      label: 'Minimum Monthly Payment ($)',
      min: 0,
      step: 10,
      required: true,
      placeholder: '200',
      group: '💳 Debt Details',
    },
    {
      id: 'debtType',
      name: 'debtType',
      type: 'select',
      label: 'Debt Type',
      required: true,
      options: [
        { value: 'credit-card', label: 'Credit Card' },
        { value: 'student-loan', label: 'Student Loan' },
        { value: 'auto-loan', label: 'Auto Loan' },
        { value: 'personal-loan', label: 'Personal Loan' },
        { value: 'mortgage', label: 'Mortgage' },
      ],
      group: '💳 Debt Details',
    },
    {
      id: 'expectedInvestmentReturn',
      name: 'expectedInvestmentReturn',
      type: 'number',
      label: 'Expected Investment Return (%)',
      min: 0,
      max: 20,
      step: 0.1,
      placeholder: '10',
      group: '📈 Investment Assumptions',
      helpText: 'S&P 500 historical avg: ~10%',
    },
    {
      id: 'employerMatch',
      name: 'employerMatch',
      type: 'number',
      label: 'Employer Match (%)',
      min: 0,
      max: 10,
      step: 0.5,
      placeholder: '0',
      group: '📈 Investment Assumptions',
      helpText: 'If investing in 401(k) with match',
    },
    {
      id: 'timeHorizonYears',
      name: 'timeHorizonYears',
      type: 'select',
      label: 'Time Horizon',
      required: true,
      options: [
        { value: '5', label: '5 years' },
        { value: '10', label: '10 years' },
        { value: '15', label: '15 years' },
        { value: '20', label: '20 years' },
      ],
      group: '📊 Analysis Settings',
    },
    {
      id: 'hasEmergencyFund',
      name: 'hasEmergencyFund',
      type: 'select',
      label: 'Emergency Fund Status',
      required: true,
      options: [
        { value: 'yes', label: 'Yes (3-6 months saved)' },
        { value: 'no', label: 'No emergency fund yet' },
      ],
      group: '📊 Analysis Settings',
      helpText: 'Critical for this decision',
    },
  ],
  clientScript: 'invest-vs-payoff-debt',
  analysisType: 'invest-vs-payoff-debt',
};
