import type { CalculatorConfig } from '../../types';

export const mortgage_scenario_planningCalculator: CalculatorConfig = {
  id: 'mortgage-scenario-planning',
  title: 'Mortgage Scenario Planner',
  description:
    'Compare multiple mortgage options, early payoff strategies, and refinancing scenarios',
  category: 'personal',
  icon: '🏡',
  color: 'green',
  keywords: ['mortgage', 'scenario', 'compare', 'early payoff', 'refinance', 'loan comparison'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How should I compare different mortgage options?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Compare monthly payments, total interest, and total cost over the life of the loan. Also consider refinancing and early payoff scenarios to see which option saves the most money long-term.',
        },
      },
      {
        '@type': 'Question',
        name: 'When should I refinance my mortgage?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Consider refinancing when you can get a lower interest rate that saves enough to cover closing costs within a reasonable timeframe, typically 2-3 years.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Models', href: '/models' },
    { name: 'Mortgage Scenario Planner', href: '/mortgage-scenario-planning' },
  ],
  formFields: [
    {
      id: 'homePrice',
      name: 'homePrice',
      type: 'number',
      label: 'Home Price',
      min: 0,
      step: 1000,
      required: true,
      group: '📋 Loan Basics',
      placeholder: '500000',
    },
    {
      id: 'loanTerm',
      name: 'loanTerm',
      type: 'select',
      label: 'Loan Term',
      required: true,
      options: [
        { value: '15', label: '15 years' },
        { value: '20', label: '20 years' },
        { value: '30', label: '30 years' },
      ],
      group: '📋 Loan Basics',
    },
    {
      id: 'scenario1Down',
      name: 'scenario1Down',
      type: 'number',
      label: 'Down Payment',
      min: 0,
      step: 1000,
      required: true,
      group: '💰 Option A: Conservative Approach',
      placeholder: '100000',
      helpText: '20%+ avoids PMI',
    },
    {
      id: 'scenario1Rate',
      name: 'scenario1Rate',
      type: 'number',
      label: 'Interest Rate (%)',
      min: 0,
      max: 30,
      step: 0.01,
      required: true,
      group: '💰 Option A: Conservative Approach',
      placeholder: '6.5',
      helpText: 'Shop 3-5 lenders for best rate',
    },
    {
      id: 'scenario1Extra',
      name: 'scenario1Extra',
      type: 'number',
      label: 'Extra Monthly Payment (Optional)',
      min: 0,
      step: 100,
      group: '💰 Option A: Conservative Approach',
      placeholder: '0',
      helpText: 'Even $100-200 saves thousands in interest',
    },
    {
      id: 'scenario2Down',
      name: 'scenario2Down',
      type: 'number',
      label: 'Down Payment',
      min: 0,
      step: 1000,
      required: true,
      group: '🏠 Option B: Alternative Approach',
      placeholder: '75000',
      helpText: 'Compare different down payment amount',
    },
    {
      id: 'scenario2Rate',
      name: 'scenario2Rate',
      type: 'number',
      label: 'Interest Rate (%)',
      min: 0,
      max: 30,
      step: 0.01,
      required: true,
      group: '🏠 Option B: Alternative Approach',
      placeholder: '7.0',
      helpText: 'Try a different rate to see impact',
    },
    {
      id: 'scenario2Extra',
      name: 'scenario2Extra',
      type: 'number',
      label: 'Extra Monthly Payment (Optional)',
      min: 0,
      step: 100,
      group: '🏠 Option B: Alternative Approach',
      placeholder: '0',
      helpText: 'Compare aggressive payoff strategy',
    },
    {
      id: 'refinanceRate',
      name: 'refinanceRate',
      type: 'number',
      label: 'Refinance Rate (%)',
      min: 0,
      max: 30,
      step: 0.01,
      group: '🔄 Refinancing (Optional)',
      helpText: 'If provided, compare refinancing after 5 years at this rate',
      placeholder: '5.5',
    },
    {
      id: 'grossMonthlyIncome',
      name: 'grossMonthlyIncome',
      type: 'number',
      label: 'Gross Monthly Income (Optional)',
      min: 0,
      step: 1000,
      group: '💵 Affordability Check (Optional)',
      helpText: 'Check if payments are within recommended debt-to-income ratios',
      placeholder: '10000',
    },
  ],
  clientScript: 'mortgage-scenario-planning',
  analysisType: 'mortgage-scenario-planning',
};
