import type { CalculatorConfig } from '../../types';

export const net_worthCalculator: CalculatorConfig = {
  id: 'net-worth',
  title: 'Net Worth Tracker',
  description: 'Track net worth over time with asset/liability breakdown and projections',
  category: 'personal',
  icon: '💰',
  color: 'green',
  keywords: ['net worth', 'assets', 'liabilities', 'wealth tracking'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How do I calculate my net worth?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Net worth is calculated by subtracting your total liabilities (debts) from your total assets. Assets include cash, investments, real estate, and retirement accounts. Liabilities include mortgages, credit card debt, student loans, and other debts.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Personal Finance', href: '/models/personal' },
    { name: 'Net Worth Tracker', href: '/calculator/net-worth' },
  ],
  formFields: [
    {
      id: 'cash',
      name: 'cash',
      type: 'number',
      label: 'Cash ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Assets',
    },
    {
      id: 'investments',
      name: 'investments',
      type: 'number',
      label: 'Investments ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Assets',
    },
    {
      id: 'realEstate',
      name: 'realEstate',
      type: 'number',
      label: 'Real Estate ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Assets',
    },
    {
      id: 'retirementAccounts',
      name: 'retirementAccounts',
      type: 'number',
      label: 'Retirement Accounts ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Assets',
    },
    {
      id: 'mortgages',
      name: 'mortgages',
      type: 'number',
      label: 'Mortgages ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Liabilities',
    },
    {
      id: 'creditCardDebt',
      name: 'creditCardDebt',
      type: 'number',
      label: 'Credit Card Debt ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Liabilities',
    },
    {
      id: 'studentLoans',
      name: 'studentLoans',
      type: 'number',
      label: 'Student Loans ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Liabilities',
    },
    {
      id: 'autoLoans',
      name: 'autoLoans',
      type: 'number',
      label: 'Auto Loans ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Liabilities',
    },
    {
      id: 'assetGrowthRate',
      name: 'assetGrowthRate',
      type: 'number',
      label: 'Asset Growth Rate (%)',
      min: 0,
      max: 20,
      step: 0.01,
      required: true,
      group: 'Projections',
    },
  ],
  clientScript: 'net-worth',
  analysisType: 'net-worth',
};
