import type { CalculatorConfig } from '../../types';

export const refinancingCalculator: CalculatorConfig = {
  id: 'refinancing',
  title: 'Refinancing Calculator',
  description:
    'Comprehensive mortgage refinancing analysis with break-even point and interest savings',
  category: 'personal',
  icon: '🔄',
  color: 'blue',
  keywords: ['refinancing', 'mortgage', 'break-even', 'interest savings'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'When should I refinance my mortgage?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Refinancing makes sense when you can get a lower interest rate, reduce your monthly payment, shorten your loan term, or access cash through a cash-out refinance. The break-even point shows when the savings offset the closing costs.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Personal Finance', href: '/models/personal' },
    { name: 'Refinancing Calculator', href: '/calculator/refinancing' },
  ],
  formFields: [
    {
      id: 'principalBalance',
      name: 'principalBalance',
      type: 'number',
      label: 'Current Principal Balance ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Current Mortgage',
    },
    {
      id: 'currentInterestRate',
      name: 'currentInterestRate',
      type: 'number',
      label: 'Current Interest Rate (%)',
      min: 0,
      max: 20,
      step: 0.01,
      required: true,
      group: 'Current Mortgage',
    },
    {
      id: 'remainingTerm',
      name: 'remainingTerm',
      type: 'number',
      label: 'Remaining Term (years)',
      min: 0,
      max: 30,
      required: true,
      group: 'Current Mortgage',
    },
    {
      id: 'monthlyPayment',
      name: 'monthlyPayment',
      type: 'number',
      label: 'Current Monthly Payment ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Current Mortgage',
    },
    {
      id: 'newInterestRate',
      name: 'newInterestRate',
      type: 'number',
      label: 'New Interest Rate (%)',
      min: 0,
      max: 20,
      step: 0.01,
      required: true,
      group: 'New Mortgage',
    },
    {
      id: 'newTerm',
      name: 'newTerm',
      type: 'number',
      label: 'New Term (years)',
      min: 5,
      max: 30,
      required: true,
      group: 'New Mortgage',
    },
    {
      id: 'refinanceType',
      name: 'refinanceType',
      type: 'select',
      label: 'Refinance Type',
      required: true,
      group: 'New Mortgage',
      options: [
        { value: 'rate-and-term', label: 'Rate and Term' },
        { value: 'cash-out', label: 'Cash Out' },
        { value: 'cash-in', label: 'Cash In' },
      ],
    },
    {
      id: 'closingCosts',
      name: 'closingCosts',
      type: 'number',
      label: 'Closing Costs ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Costs',
    },
  ],
  clientScript: 'refinancing',
  analysisType: 'refinancing',
};
