import type { CalculatorConfig } from '../../types';

export const rent_vs_buyCalculator: CalculatorConfig = {
  id: 'rent-vs-buy',
  title: 'Rent vs Buy Calculator',
  description:
    'Compare the financial impact of renting versus buying a home over time, including equity, tax benefits, and opportunity costs',
  category: 'personal',
  icon: '🏠',
  color: 'blue',
  keywords: ['rent', 'buy', 'homeownership', 'real estate', 'housing decision'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'Is it better to rent or buy a home?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'It depends on your local market, how long you plan to stay, home prices, rent costs, and interest rates. Generally, buying makes more sense if you plan to stay 5+ years.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is the break-even point for buying vs renting?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'The break-even point is when the total costs of buying (including mortgage, taxes, maintenance) minus equity built equals the total cost of renting. This typically occurs between 3-7 years depending on market conditions.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Models', href: '/models' },
    { name: 'Rent vs Buy', href: '/calculator/rent-vs-buy' },
  ],
  formFields: [
    {
      id: 'homePrice',
      name: 'homePrice',
      type: 'number',
      label: 'Home Price ($)',
      min: 0,
      step: 1000,
      required: true,
      placeholder: '500000',
      group: '🏠 Home Purchase Details',
    },
    {
      id: 'downPayment',
      name: 'downPayment',
      type: 'number',
      label: 'Down Payment ($)',
      min: 0,
      step: 1000,
      required: true,
      placeholder: '100000',
      group: '🏠 Home Purchase Details',
      helpText: '20% avoids PMI',
    },
    {
      id: 'interestRate',
      name: 'interestRate',
      type: 'number',
      label: 'Mortgage Interest Rate (%)',
      min: 0,
      max: 15,
      step: 0.01,
      required: true,
      placeholder: '6.5',
      group: '🏠 Home Purchase Details',
    },
    {
      id: 'loanTermYears',
      name: 'loanTermYears',
      type: 'select',
      label: 'Loan Term',
      required: true,
      options: [
        { value: '10', label: '10 years' },
        { value: '15', label: '15 years' },
        { value: '20', label: '20 years' },
        { value: '30', label: '30 years' },
      ],
      group: '🏠 Home Purchase Details',
    },
    {
      id: 'propertyTaxRate',
      name: 'propertyTaxRate',
      type: 'number',
      label: 'Property Tax Rate (%)',
      min: 0,
      max: 5,
      step: 0.1,
      placeholder: '1.2',
      group: '💰 Ownership Costs',
      helpText: 'Annual property tax as % of home value',
    },
    {
      id: 'propertyTaxIncreaseRate',
      name: 'propertyTaxIncreaseRate',
      type: 'number',
      label: 'Property Tax Annual Increase (%)',
      min: 0,
      max: 10,
      step: 0.1,
      placeholder: '2',
      group: '💰 Ownership Costs',
      helpText: 'Annual increase separate from appreciation',
      advancedOnly: true,
    },
    {
      id: 'homeInsurance',
      name: 'homeInsurance',
      type: 'number',
      label: 'Home Insurance ($/month)',
      min: 0,
      step: 10,
      placeholder: '150',
      group: '💰 Ownership Costs',
    },
    {
      id: 'hoaFees',
      name: 'hoaFees',
      type: 'number',
      label: 'HOA Fees ($/month)',
      min: 0,
      step: 10,
      placeholder: '0',
      group: '💰 Ownership Costs',
    },
    {
      id: 'maintenanceRate',
      name: 'maintenanceRate',
      type: 'number',
      label: 'Annual Maintenance (%)',
      min: 0,
      max: 5,
      step: 0.1,
      placeholder: '1',
      group: '💰 Ownership Costs',
      helpText: 'Typically 1% of home value per year',
    },
    {
      id: 'monthlyRent',
      name: 'monthlyRent',
      type: 'number',
      label: 'Monthly Rent ($)',
      min: 0,
      step: 50,
      required: true,
      placeholder: '2500',
      group: '🏢 Rental Details',
    },
    {
      id: 'rentIncreaseRate',
      name: 'rentIncreaseRate',
      type: 'number',
      label: 'Annual Rent Increase (%)',
      min: 0,
      max: 20,
      step: 0.1,
      placeholder: '3',
      group: '🏢 Rental Details',
    },
    {
      id: 'rentersInsurance',
      name: 'rentersInsurance',
      type: 'number',
      label: 'Renters Insurance ($/month)',
      min: 0,
      step: 5,
      placeholder: '20',
      group: '🏢 Rental Details',
    },
    {
      id: 'securityDepositMonths',
      name: 'securityDepositMonths',
      type: 'select',
      label: 'Security Deposit',
      options: [
        { value: '0', label: 'None' },
        { value: '1', label: '1 month' },
        { value: '2', label: '2 months' },
        { value: '3', label: '3 months' },
      ],
      group: '🏢 Rental Details',
      helpText: 'Months of rent held as deposit',
      advancedOnly: true,
    },
    {
      id: 'yearsToAnalyze',
      name: 'yearsToAnalyze',
      type: 'select',
      label: 'Analysis Period',
      required: true,
      options: [
        { value: '3', label: '3 years' },
        { value: '5', label: '5 years' },
        { value: '7', label: '7 years' },
        { value: '10', label: '10 years' },
        { value: '15', label: '15 years' },
        { value: '20', label: '20 years' },
        { value: '25', label: '25 years' },
        { value: '30', label: '30 years' },
      ],
      group: '📊 Analysis Settings',
      helpText: 'How long do you plan to stay?',
    },
    {
      id: 'appreciationRate',
      name: 'appreciationRate',
      type: 'number',
      label: 'Home Appreciation Rate (%)',
      min: -5,
      max: 15,
      step: 0.1,
      placeholder: '3',
      group: '📊 Analysis Settings',
      helpText: 'Historical average: 3-4% annually',
    },
    {
      id: 'investmentReturnRate',
      name: 'investmentReturnRate',
      type: 'number',
      label: 'Investment Return Rate (%)',
      min: 0,
      max: 20,
      step: 0.1,
      placeholder: '7',
      group: '📊 Analysis Settings',
      helpText: 'Return on invested down payment savings',
    },
    {
      id: 'inflationRate',
      name: 'inflationRate',
      type: 'number',
      label: 'Inflation Rate (%)',
      min: 0,
      max: 15,
      step: 0.1,
      placeholder: '2.5',
      group: '📊 Analysis Settings',
      helpText: 'For real vs nominal value comparison',
      advancedOnly: true,
    },
    {
      id: 'marginalTaxRate',
      name: 'marginalTaxRate',
      type: 'number',
      label: 'Marginal Tax Rate (%)',
      min: 0,
      max: 50,
      step: 1,
      placeholder: '22',
      group: '📊 Analysis Settings',
      helpText: 'For mortgage interest deduction',
    },
    {
      id: 'filingStatus',
      name: 'filingStatus',
      type: 'select',
      label: 'Tax Filing Status',
      required: false,
      options: [
        { value: 'single', label: 'Single' },
        { value: 'married', label: 'Married Filing Jointly' },
        { value: 'head', label: 'Head of Household' },
      ],
      group: '📊 Analysis Settings',
      helpText: 'For standard deduction comparison',
      advancedOnly: true,
    },
    {
      id: 'otherItemizedDeductions',
      name: 'otherItemizedDeductions',
      type: 'number',
      label: 'Other Itemized Deductions ($)',
      min: 0,
      max: 100000,
      step: 100,
      placeholder: '0',
      group: '📊 Analysis Settings',
      helpText: 'State/local taxes, charity, etc.',
      advancedOnly: true,
    },
    {
      id: 'closingCostRate',
      name: 'closingCostRate',
      type: 'number',
      label: 'Closing Costs (%)',
      min: 0,
      max: 10,
      step: 0.1,
      placeholder: '3',
      group: '💵 Transaction Costs (Optional)',
      helpText: 'Typically 2-5% of home price',
    },
    {
      id: 'sellingCostRate',
      name: 'sellingCostRate',
      type: 'number',
      label: 'Selling Costs (%)',
      min: 0,
      max: 10,
      step: 0.1,
      placeholder: '6',
      group: '💵 Transaction Costs (Optional)',
      helpText: 'Agent commissions typically 5-6%',
    },
  ],
  clientScript: 'rent-vs-buy',
  analysisType: 'rent-vs-buy',
};
