import type { CalculatorConfig } from '../../types';

export const roth_vs_traditional_iraCalculator: CalculatorConfig = {
  id: 'roth-vs-traditional-ira',
  title: 'Roth vs Traditional IRA Calculator',
  description:
    'Compare Roth and Traditional IRA strategies including tax brackets, RMDs, and conversions',
  category: 'personal',
  icon: '🏦',
  color: 'violet',
  keywords: ['Roth IRA', 'Traditional IRA', 'retirement', 'tax', 'RMD', 'conversion'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'Roth or Traditional IRA — which is better?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'It depends on your current vs expected retirement tax rate, time horizon, and whether you need upfront tax deductions. This calculator compares both paths with your inputs.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Personal Tools', href: '/models/personal' },
    { name: 'Roth vs Traditional IRA', href: '/calculator/roth-vs-traditional-ira' },
  ],
  formFields: [
    {
      id: 'age',
      name: 'age',
      type: 'number',
      label: 'Current Age',
      min: 18,
      max: 100,
      step: 1,
      required: true,
      group: 'Personal Info',
    },
    {
      id: 'retirementAge',
      name: 'retirementAge',
      type: 'number',
      label: 'Retirement Age',
      min: 50,
      max: 100,
      step: 1,
      required: true,
      group: 'Personal Info',
    },
    {
      id: 'annualContribution',
      name: 'annualContribution',
      type: 'number',
      label: 'Annual Contribution ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Contributions',
    },
    {
      id: 'catchUpContribution',
      name: 'catchUpContribution',
      type: 'number',
      label: 'Catch-Up Contribution ($)',
      min: 0,
      step: 100,
      required: false,
      group: 'Contributions',
    },
    {
      id: 'yearsToContribute',
      name: 'yearsToContribute',
      type: 'number',
      label: 'Years to Contribute',
      min: 1,
      max: 50,
      step: 1,
      required: true,
      group: 'Contributions',
    },
    {
      id: 'currentTraditionalBalance',
      name: 'currentTraditionalBalance',
      type: 'number',
      label: 'Current Traditional IRA Balance ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Account Balances',
    },
    {
      id: 'currentRothBalance',
      name: 'currentRothBalance',
      type: 'number',
      label: 'Current Roth IRA Balance ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Account Balances',
    },
    {
      id: 'expectedReturn',
      name: 'expectedReturn',
      type: 'number',
      label: 'Expected Annual Return (decimal, e.g. 0.07)',
      min: 0,
      max: 1,
      step: 0.01,
      required: true,
      group: 'Account Balances',
    },
    {
      id: 'currentMarginalTaxRate',
      name: 'currentMarginalTaxRate',
      type: 'number',
      label: 'Current Marginal Tax Rate (decimal)',
      min: 0,
      max: 1,
      step: 0.01,
      required: true,
      group: 'Tax Info',
    },
    {
      id: 'expectedRetirementMarginalTaxRate',
      name: 'expectedRetirementMarginalTaxRate',
      type: 'number',
      label: 'Expected Retirement Marginal Tax Rate (decimal)',
      min: 0,
      max: 1,
      step: 0.01,
      required: true,
      group: 'Tax Info',
    },
    {
      id: 'stateTaxRate',
      name: 'stateTaxRate',
      type: 'number',
      label: 'State Tax Rate (decimal)',
      min: 0,
      max: 1,
      step: 0.01,
      required: true,
      group: 'Tax Info',
    },
    {
      id: 'stateTaxDeduction',
      name: 'stateTaxDeduction',
      type: 'checkbox',
      label: 'State allows IRA deduction',
      required: false,
      group: 'Tax Info',
    },
    {
      id: 'annualWithdrawalAmount',
      name: 'annualWithdrawalAmount',
      type: 'number',
      label: 'Annual Withdrawal Amount ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Withdrawals',
    },
    {
      id: 'withdrawalStartAge',
      name: 'withdrawalStartAge',
      type: 'number',
      label: 'Withdrawal Start Age',
      min: 50,
      max: 100,
      step: 1,
      required: true,
      group: 'Withdrawals',
    },
    {
      id: 'includeRequiredMinimumDistributions',
      name: 'includeRequiredMinimumDistributions',
      type: 'checkbox',
      label: 'Include required minimum distributions',
      required: false,
      group: 'Withdrawals',
    },
    {
      id: 'rmdsStartAge',
      name: 'rmdsStartAge',
      type: 'number',
      label: 'RMD Start Age',
      min: 70,
      max: 80,
      step: 1,
      required: true,
      group: 'Withdrawals',
    },
    {
      id: 'includeConversionAnalysis',
      name: 'includeConversionAnalysis',
      type: 'checkbox',
      label: 'Include conversion analysis',
      required: false,
      group: 'Analysis Options',
    },
    {
      id: 'includeTaxBracketOptimization',
      name: 'includeTaxBracketOptimization',
      type: 'checkbox',
      label: 'Include tax bracket optimization',
      required: false,
      group: 'Analysis Options',
    },
    {
      id: 'projectionYears',
      name: 'projectionYears',
      type: 'number',
      label: 'Projection Years',
      min: 1,
      max: 50,
      step: 1,
      required: true,
      group: 'Analysis Options',
    },
  ],
  clientScript: 'roth-vs-traditional-ira',
  analysisType: 'roth-vs-traditional-ira',
};
