import type { CalculatorConfig } from '../../types';

export const side_hustle_incomeCalculator: CalculatorConfig = {
  id: 'side-hustle-income',
  title: 'Side Hustle Income Calculator',
  description:
    'Calculate true after-tax income from freelance/gig work including self-employment tax, quarterly estimated taxes, and business deductions',
  category: 'personal',
  icon: '💰',
  color: 'yellow',
  keywords: ['freelance', 'self-employed', 'side hustle', 'gig economy', '1099', 'taxes'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How much is self-employment tax?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Self-employment tax is 15.3% (12.4% Social Security + 2.9% Medicare) on 92.35% of your net profit. This covers both employee and employer portions of FICA.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Models', href: '/models' },
    { name: 'Side Hustle Income', href: '/calculator/side-hustle-income' },
  ],
  formFields: [
    {
      id: 'monthlyRevenue',
      name: 'monthlyRevenue',
      type: 'number',
      label: 'Monthly Revenue ($)',
      min: 0,
      step: 100,
      required: true,
      placeholder: '5000',
      group: '💼 Business Income',
      helpText: 'Gross revenue before expenses',
    },
    {
      id: 'hoursPerWeek',
      name: 'hoursPerWeek',
      type: 'number',
      label: 'Hours Per Week',
      min: 0,
      step: 1,
      required: true,
      placeholder: '20',
      group: '💼 Business Income',
    },
    {
      id: 'businessExpenses',
      name: 'businessExpenses',
      type: 'number',
      label: 'Monthly Business Expenses ($)',
      min: 0,
      step: 50,
      placeholder: '500',
      group: '💼 Business Income',
      helpText: 'Deductible expenses: software, equipment, mileage, etc.',
    },
    {
      id: 'filingStatus',
      name: 'filingStatus',
      type: 'select',
      label: 'Filing Status',
      required: true,
      options: [
        { value: 'single', label: 'Single' },
        { value: 'married', label: 'Married Filing Jointly' },
        { value: 'head-of-household', label: 'Head of Household' },
      ],
      group: '📋 Tax Info',
    },
    {
      id: 'otherIncome',
      name: 'otherIncome',
      type: 'number',
      label: 'Other Annual Income ($)',
      min: 0,
      step: 1000,
      placeholder: '0',
      group: '📋 Tax Info',
      helpText: 'W-2 wages, investment income, etc.',
    },
    {
      id: 'stateTaxRate',
      name: 'stateTaxRate',
      type: 'number',
      label: 'State Tax Rate (%)',
      min: 0,
      max: 15,
      step: 0.1,
      placeholder: '5',
      group: '📋 Tax Info',
    },
    {
      id: 'selfEmploymentTaxDeduction',
      name: 'selfEmploymentTaxDeduction',
      type: 'select',
      label: 'Deduct Half of SE Tax?',
      options: [
        { value: 'yes', label: 'Yes (recommended)' },
        { value: 'no', label: 'No' },
      ],
      group: '💡 Deductions (Optional)',
      helpText: 'You can deduct 50% of SE tax',
    },
    {
      id: 'qbiDeduction',
      name: 'qbiDeduction',
      type: 'select',
      label: 'Qualify for QBI Deduction?',
      options: [
        { value: 'yes', label: 'Yes (20% deduction)' },
        { value: 'no', label: 'No' },
      ],
      group: '💡 Deductions (Optional)',
      helpText: 'Qualified Business Income deduction',
    },
  ],
  clientScript: 'side-hustle-income',
  analysisType: 'side-hustle-income',
};
