import type { CalculatorConfig } from '../../types';

export const social_securityCalculator: CalculatorConfig = {
  id: 'social-security',
  title: 'Social Security Optimizer',
  description:
    'Optimize your Social Security claiming strategy with break-even analysis and benefit projections',
  category: 'personal',
  icon: '👴',
  color: 'blue',
  keywords: ['social security', 'retirement', 'benefits', 'claiming strategy'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'When should I claim Social Security benefits?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'The optimal claiming age depends on your life expectancy, financial needs, and marital status. Generally, claiming at 70 provides the highest monthly benefit, while claiming at 62 provides benefits sooner but at a reduced rate.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Personal Finance', href: '/models/personal' },
    { name: 'Social Security Optimizer', href: '/calculator/social-security' },
  ],
  formFields: [
    {
      id: 'birthDate',
      name: 'birthDate',
      type: 'text',
      label: 'Birth Date',
      required: true,
      group: 'Personal Information',
    },
    {
      id: 'currentAge',
      name: 'currentAge',
      type: 'number',
      label: 'Current Age',
      min: 62,
      max: 70,
      required: true,
      group: 'Personal Information',
    },
    {
      id: 'fullRetirementAge',
      name: 'fullRetirementAge',
      type: 'number',
      label: 'Full Retirement Age',
      min: 66,
      max: 67,
      step: 0.1,
      required: true,
      group: 'Personal Information',
    },
    {
      id: 'lifeExpectancy',
      name: 'lifeExpectancy',
      type: 'number',
      label: 'Life Expectancy',
      min: 70,
      max: 100,
      required: true,
      group: 'Personal Information',
    },
    {
      id: 'maritalStatus',
      name: 'maritalStatus',
      type: 'select',
      label: 'Marital Status',
      required: true,
      group: 'Personal Information',
      options: [
        { value: 'single', label: 'Single' },
        { value: 'married', label: 'Married' },
        { value: 'divorced', label: 'Divorced' },
        { value: 'widowed', label: 'Widowed' },
      ],
    },
    {
      id: 'currentAnnualEarnings',
      name: 'currentAnnualEarnings',
      type: 'number',
      label: 'Current Annual Earnings ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Earnings',
    },
    {
      id: 'averageLifetimeEarnings',
      name: 'averageLifetimeEarnings',
      type: 'number',
      label: 'Average Lifetime Earnings ($)',
      min: 0,
      step: 1000,
      group: 'Earnings',
    },
    {
      id: 'primaryClaimingAge',
      name: 'primaryClaimingAge',
      type: 'number',
      label: 'Primary Claiming Age',
      min: 62,
      max: 70,
      required: true,
      group: 'Claiming Strategy',
    },
    {
      id: 'optimizeFor',
      name: 'optimizeFor',
      type: 'select',
      label: 'Optimize For',
      required: true,
      group: 'Claiming Strategy',
      options: [
        { value: 'maximum-lifetime', label: 'Maximum Lifetime Benefits' },
        { value: 'maximum-monthly', label: 'Maximum Monthly Benefit' },
        { value: 'survivor-benefits', label: 'Survivor Benefits' },
        { value: 'spousal-benefits', label: 'Spousal Benefits' },
      ],
    },
  ],
  clientScript: 'social-security',
  analysisType: 'social-security',
};
