# Cloudflare Pages deployment for the web app
name = "financial-analysis-web"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "apps/web"

[build.upload]
format = "service-worker"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Pages configuration
[[pages_build_config]]
# Build command and output directory are handled by the build config above
build_command = "npm run build"
destination_dir = "dist"

# Custom domains (uncomment and configure as needed)
# [[pages_build_config.domains]]
# domain = "your-domain.com"