/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: a8cb22a71bbdcd7e371b291f254dd020)
interface __BaseEnv_Env {
	ENVIRONMENT?: "development" | "preview" | "production";
	WORKER_ROLE?: "indexer";
	COMMIT_SHA?: "local" | "preview" | "production";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface DevelopmentEnv {
		ENVIRONMENT: "development";
		WORKER_ROLE: "indexer";
		COMMIT_SHA: "local";
	}
	interface PreviewEnv {
		ENVIRONMENT: "preview";
		WORKER_ROLE: "indexer";
		COMMIT_SHA: "preview";
	}
	interface ProductionEnv {
		ENVIRONMENT: "production";
		WORKER_ROLE: "indexer";
		COMMIT_SHA: "production";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "WORKER_ROLE" | "COMMIT_SHA">> {}
}
