import type { CalculatorConfig } from '../../types';

export const business_valuationCalculator: CalculatorConfig = {
  id: 'business-valuation',
  title: 'Business Valuation Calculator',
  description:
    'Estimate business value using industry multiples, EBITDA, revenue, and asset-based methods',
  category: 'business',
  icon: '🏢',
  color: 'indigo',
  keywords: ['business valuation', 'EBITDA multiple', 'revenue multiple', 'enterprise value'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How is a small business typically valued?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Small businesses are often valued using a blend of revenue multiples, EBITDA multiples, and asset-based adjustments for risk and growth.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Business Valuation', href: '/calculator/business-valuation' },
  ],
  formFields: [
    {
      id: 'industry',
      name: 'industry',
      type: 'select',
      label: 'Industry',
      required: true,
      options: [
        { value: 'saas', label: 'SaaS / Software' },
        { value: 'retail', label: 'Retail' },
        { value: 'services', label: 'Professional Services' },
        { value: 'manufacturing', label: 'Manufacturing' },
        { value: 'healthcare', label: 'Healthcare' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      id: 'businessAge',
      name: 'businessAge',
      type: 'number',
      label: 'Business Age (Years)',
      min: 0,
      step: 1,
      required: true,
    },
    {
      id: 'annualRevenue',
      name: 'annualRevenue',
      type: 'number',
      label: 'Annual Revenue ($)',
      min: 0,
      step: 1000,
      required: true,
    },
    {
      id: 'annualEbitda',
      name: 'annualEbitda',
      type: 'number',
      label: 'Annual EBITDA ($)',
      step: 1000,
      required: true,
      helpText: 'Can be negative for early-stage businesses',
    },
    {
      id: 'annualNetIncome',
      name: 'annualNetIncome',
      type: 'number',
      label: 'Annual Net Income ($)',
      step: 1000,
      required: true,
    },
    {
      id: 'totalAssets',
      name: 'totalAssets',
      type: 'number',
      label: 'Total Assets ($)',
      min: 0,
      step: 1000,
      required: true,
    },
    {
      id: 'totalLiabilities',
      name: 'totalLiabilities',
      type: 'number',
      label: 'Total Liabilities ($)',
      min: 0,
      step: 1000,
      required: true,
    },
    {
      id: 'revenueGrowthRate',
      name: 'revenueGrowthRate',
      type: 'number',
      label: 'Revenue Growth Rate (%)',
      step: 0.1,
      required: true,
    },
    {
      id: 'inventoryValue',
      name: 'inventoryValue',
      type: 'number',
      label: 'Inventory Value ($)',
      min: 0,
      step: 100,
      required: false,
      group: 'Optional Details',
    },
    {
      id: 'equipmentValue',
      name: 'equipmentValue',
      type: 'number',
      label: 'Equipment Value ($)',
      min: 0,
      step: 100,
      required: false,
      group: 'Optional Details',
    },
    {
      id: 'customerCount',
      name: 'customerCount',
      type: 'number',
      label: 'Customer Count',
      min: 0,
      step: 1,
      required: false,
      group: 'Optional Details',
    },
    {
      id: 'customerConcentration',
      name: 'customerConcentration',
      type: 'number',
      label: 'Top Customer Revenue Share (%)',
      min: 0,
      max: 100,
      step: 1,
      required: false,
      group: 'Optional Details',
    },
    {
      id: 'ownerDependency',
      name: 'ownerDependency',
      type: 'select',
      label: 'Owner Dependency',
      required: false,
      group: 'Optional Details',
      options: [
        { value: 'low', label: 'Low' },
        { value: 'medium', label: 'Medium' },
        { value: 'high', label: 'High' },
      ],
    },
    {
      id: 'hasRecurringRevenue',
      name: 'hasRecurringRevenue',
      type: 'checkbox',
      label: 'Recurring revenue model',
      required: false,
      group: 'Optional Details',
    },
    {
      id: 'hasDocumentedProcesses',
      name: 'hasDocumentedProcesses',
      type: 'checkbox',
      label: 'Documented operating processes',
      required: false,
      group: 'Optional Details',
    },
  ],
  clientScript: 'business-valuation',
  analysisType: 'business-valuation',
};
