import type { CalculatorConfig } from '../../types';

export const business_financial_healthCalculator: CalculatorConfig = {
  id: 'business-financial-health',
  title: 'Business Financial Health Assessment',
  description:
    'Assess your business financial health with debt-to-EBITDA, current ratio, quick ratio, and credit score analysis',
  category: 'business',
  icon: '🏥',
  color: 'orange',
  keywords: ['business health', 'financial health', 'debt capacity', 'liquidity', 'credit score'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is a good debt-to-EBITDA ratio?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'A debt-to-EBITDA ratio below 3x is considered healthy. Above 5x indicates high leverage and may limit borrowing capacity.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is the current ratio and why does it matter?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Current ratio measures liquidity by comparing current assets to current liabilities. A ratio above 1.5 indicates good liquidity, below 1.0 suggests liquidity concerns.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Financial Health', href: '/calculator/business-financial-health' },
  ],
  formFields: [
    {
      id: 'yearsInBusiness',
      name: 'yearsInBusiness',
      type: 'number',
      label: 'Years in Business',
      min: 0,
      max: 100,
      step: 1,
      required: true,
    },
    {
      id: 'annualRevenue',
      name: 'annualRevenue',
      type: 'number',
      label: 'Annual Revenue ($)',
      min: 0,
      step: 10000,
      required: true,
    },
    {
      id: 'annualEBITDA',
      name: 'annualEBITDA',
      type: 'number',
      label: 'Annual EBITDA ($)',
      step: 10000,
      required: true,
    },
    {
      id: 'currentDebt',
      name: 'currentDebt',
      type: 'number',
      label: 'Current Debt ($)',
      min: 0,
      step: 10000,
      required: true,
    },
    {
      id: 'monthlyDebtPayments',
      name: 'monthlyDebtPayments',
      type: 'number',
      label: 'Monthly Debt Payments ($)',
      min: 0,
      step: 1000,
      required: true,
    },
    {
      id: 'cashOnHand',
      name: 'cashOnHand',
      type: 'number',
      label: 'Cash on Hand ($)',
      min: 0,
      step: 10000,
      required: true,
    },
    {
      id: 'accountsReceivable',
      name: 'accountsReceivable',
      type: 'number',
      label: 'Accounts Receivable ($)',
      min: 0,
      step: 10000,
      default: 0,
    },
    {
      id: 'accountsPayable',
      name: 'accountsPayable',
      type: 'number',
      label: 'Accounts Payable ($)',
      min: 0,
      step: 10000,
      default: 0,
    },
    {
      id: 'creditScore',
      name: 'creditScore',
      type: 'number',
      label: 'Business Credit Score (Optional)',
      min: 300,
      max: 850,
      step: 1,
    },
  ],
  clientScript: 'business-financial-health',
  analysisType: 'business-financial-health',
};
