import type { CalculatorConfig } from '../../types';

export const business_loan_qualifierCalculator: CalculatorConfig = {
  id: 'business-loan-qualifier',
  title: 'Business Loan Qualifier',
  description:
    'Find out which business loans you qualify for including SBA 7(a), SBA 504, bank term loans, and lines of credit',
  category: 'business',
  icon: '🏦',
  color: 'purple',
  keywords: [
    'business loan',
    'SBA',
    'DSCR',
    'LTV',
    'loan qualification',
    'financing',
    'approval odds',
  ],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is DSCR and why does it matter?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Debt Service Coverage Ratio (DSCR) measures your ability to repay debt. Lenders want 1.25+ meaning you earn $1.25 for every $1 of debt payments.',
        },
      },
      {
        '@type': 'Question',
        name: "What's the difference between SBA 7(a) and SBA 504?",
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'SBA 7(a) is flexible for any business purpose up to $5M. SBA 504 is only for real estate/equipment but offers better rates and terms up to $5.5M.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Loan Qualifier', href: '/calculator/business-loan-qualifier' },
  ],
  formFields: [
    {
      id: 'loanAmount',
      name: 'loanAmount',
      type: 'number',
      label: 'Desired Loan Amount',
      placeholder: '250000',
      min: 1,
      step: 1000,
      required: true,
    },
    {
      id: 'businessRevenue',
      name: 'businessRevenue',
      type: 'number',
      label: 'Annual Business Revenue',
      placeholder: '500000',
      min: 1,
      step: 1000,
      required: true,
    },
    {
      id: 'netIncome',
      name: 'netIncome',
      type: 'number',
      label: 'Annual Net Income',
      placeholder: '80000',
      min: 1,
      step: 1000,
      required: true,
      helpText: 'Business must be profitable',
    },
    {
      id: 'existingDebtPayments',
      name: 'existingDebtPayments',
      type: 'number',
      label: 'Existing Monthly Debt Payments',
      placeholder: '2000',
      min: 0,
      step: 100,
      required: true,
    },
    {
      id: 'businessAge',
      name: 'businessAge',
      type: 'number',
      label: 'Business Age (Years)',
      placeholder: '3',
      min: 0,
      max: 100,
      step: 0.5,
      required: true,
    },
    {
      id: 'creditScore',
      name: 'creditScore',
      type: 'number',
      label: 'Credit Score',
      placeholder: '720',
      min: 300,
      max: 850,
      step: 1,
      required: true,
    },
    {
      id: 'collateralValue',
      name: 'collateralValue',
      type: 'number',
      label: 'Collateral Value',
      placeholder: '300000',
      min: 0,
      step: 1000,
      helpText: 'Optional: Value of assets to secure loan',
    },
    {
      id: 'loanPurpose',
      name: 'loanPurpose',
      type: 'select',
      label: 'Loan Purpose',
      required: true,
      options: [
        { value: 'working-capital', label: 'Working Capital' },
        { value: 'equipment', label: 'Equipment Purchase' },
        { value: 'real-estate', label: 'Real Estate' },
        { value: 'expansion', label: 'Business Expansion' },
        { value: 'acquisition', label: 'Business Acquisition' },
      ],
    },
    {
      id: 'personalGuaranteeAvailable',
      name: 'personalGuaranteeAvailable',
      type: 'select',
      label: 'Personal Guarantee Available?',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
      ],
    },
  ],
  clientScript: 'business-loan-qualifier',
  analysisType: 'business-loan-qualifier',
};
