import type { CalculatorConfig } from '../../types';

export const business_loan_scenariosCalculator: CalculatorConfig = {
  id: 'business-loan-scenarios',
  title: 'Business Loan Scenario Comparison',
  description:
    'Compare different business loan scenarios with varying terms, rates, and structures',
  category: 'business',
  icon: '⚖️',
  color: 'purple',
  keywords: ['loan comparison', 'loan scenarios', 'loan terms', 'interest rates'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How do I compare different loan scenarios?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Enter multiple scenarios with different terms and rates. The calculator shows monthly payments, total interest, and total cost for each, helping you identify the most cost-effective option.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Loan Scenarios', href: '/calculator/business-loan-scenarios' },
  ],
  formFields: [
    {
      id: 'loanAmount',
      name: 'loanAmount',
      type: 'number',
      label: 'Loan Amount ($)',
      min: 0,
      step: 10000,
      required: true,
    },
    {
      id: 'currentDebtPayments',
      name: 'currentDebtPayments',
      type: 'number',
      label: 'Current Monthly Debt Payments ($)',
      min: 0,
      step: 1000,
      default: 0,
    },
    {
      id: 'scenario1Name',
      name: 'scenario1Name',
      type: 'text',
      label: 'Scenario 1 Name',
      placeholder: '5-Year Term Loan',
      required: true,
    },
    {
      id: 'scenario1Term',
      name: 'scenario1Term',
      type: 'number',
      label: 'Scenario 1 Term (Years)',
      min: 1,
      max: 30,
      step: 1,
      required: true,
    },
    {
      id: 'scenario1Rate',
      name: 'scenario1Rate',
      type: 'number',
      label: 'Scenario 1 Rate (%)',
      min: 0,
      max: 20,
      step: 0.1,
      required: true,
    },
    {
      id: 'scenario2Name',
      name: 'scenario2Name',
      type: 'text',
      label: 'Scenario 2 Name',
      placeholder: '7-Year Term Loan',
    },
    {
      id: 'scenario2Term',
      name: 'scenario2Term',
      type: 'number',
      label: 'Scenario 2 Term (Years)',
      min: 1,
      max: 30,
      step: 1,
    },
    {
      id: 'scenario2Rate',
      name: 'scenario2Rate',
      type: 'number',
      label: 'Scenario 2 Rate (%)',
      min: 0,
      max: 20,
      step: 0.1,
    },
  ],
  clientScript: 'business-loan-scenarios',
  analysisType: 'business-loan-scenarios',
};
