import type { CalculatorConfig } from '../../types';

export const capital_structureCalculator: CalculatorConfig = {
  id: 'capital-structure',
  title: 'Capital Structure Optimization',
  description: 'Optimize capital structure with WACC optimization and debt capacity analysis',
  category: 'business',
  icon: '⚖️',
  color: 'purple',
  keywords: ['capital structure', 'wacc', 'debt', 'equity', 'financing'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is WACC?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'WACC (Weighted Average Cost of Capital) is the average rate a company pays to finance its assets. It represents the minimum return a company must earn on its investments.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Capital Structure', href: '/calculator/capital-structure' },
  ],
  formFields: [
    {
      id: 'marketCap',
      name: 'marketCap',
      type: 'number',
      label: 'Market Cap ($)',
      min: 0,
      step: 1000000,
      required: true,
      group: 'Company Info',
    },
    {
      id: 'currentDebt',
      name: 'currentDebt',
      type: 'number',
      label: 'Current Debt ($)',
      min: 0,
      step: 1000000,
      required: true,
      group: 'Company Info',
    },
    {
      id: 'annualEBITDA',
      name: 'annualEBITDA',
      type: 'number',
      label: 'Annual EBITDA ($)',
      required: true,
      group: 'Financials',
    },
    {
      id: 'taxRate',
      name: 'taxRate',
      type: 'number',
      label: 'Tax Rate (%)',
      min: 0,
      max: 50,
      step: 0.01,
      required: true,
      group: 'Financials',
    },
    {
      id: 'riskFreeRate',
      name: 'riskFreeRate',
      type: 'number',
      label: 'Risk-Free Rate (%)',
      min: 0,
      max: 10,
      step: 0.01,
      required: true,
      group: 'Market Data',
    },
    {
      id: 'beta',
      name: 'beta',
      type: 'number',
      label: 'Beta',
      min: 0,
      max: 5,
      step: 0.01,
      required: true,
      group: 'Market Data',
    },
  ],
  clientScript: 'capital-structure',
  analysisType: 'capital-structure',
};
