import type { CalculatorConfig } from '../../types';

export const cash_flow_forecastCalculator: CalculatorConfig = {
  id: 'cash-flow-forecast',
  title: 'Cash Flow Forecasting Calculator',
  description:
    'Project your cash flow for the next 12 months including AR/AP timing, working capital needs, and cash runway analysis',
  category: 'business',
  icon: '💵',
  color: 'green',
  keywords: [
    'cash flow',
    'forecasting',
    'working capital',
    'burn rate',
    'runway',
    'AR',
    'AP',
    'DSO',
    'DPO',
  ],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'Why is cash flow more important than profit?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'You can be profitable on paper but run out of cash due to timing differences. Cash flow shows actual money in/out and determines if you can pay bills.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is cash runway?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Cash runway is how many months your business can operate before running out of cash, assuming current burn rate continues.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Cash Flow Forecast', href: '/calculator/cash-flow-forecast' },
  ],
  formFields: [
    {
      id: 'startingCash',
      name: 'startingCash',
      type: 'number',
      label: 'Starting Cash Balance',
      placeholder: '100000',
      min: 0,
      step: 100,
      required: true,
    },
    {
      id: 'monthlyRevenue',
      name: 'monthlyRevenue',
      type: 'number',
      label: 'Monthly Revenue',
      placeholder: '50000',
      min: 0,
      step: 100,
      required: true,
    },
    {
      id: 'revenueGrowthRate',
      name: 'revenueGrowthRate',
      type: 'number',
      label: 'Revenue Growth Rate (%/year)',
      placeholder: '20',
      min: -100,
      max: 1000,
      step: 0.1,
      required: true,
    },
    {
      id: 'averageCollectionDays',
      name: 'averageCollectionDays',
      type: 'number',
      label: 'Days to Collect Payment (DSO)',
      placeholder: '45',
      min: 0,
      max: 365,
      step: 1,
      required: true,
      helpText: 'How long customers take to pay invoices',
    },
    {
      id: 'monthlyExpenses',
      name: 'monthlyExpenses',
      type: 'number',
      label: 'Monthly Expenses',
      placeholder: '40000',
      min: 0,
      step: 100,
      required: true,
    },
    {
      id: 'expenseGrowthRate',
      name: 'expenseGrowthRate',
      type: 'number',
      label: 'Expense Growth Rate (%/year)',
      placeholder: '10',
      min: -100,
      max: 1000,
      step: 0.1,
      required: true,
    },
    {
      id: 'averagePaymentDays',
      name: 'averagePaymentDays',
      type: 'number',
      label: 'Days to Pay Vendors (DPO)',
      placeholder: '30',
      min: 0,
      max: 365,
      step: 1,
      required: true,
      helpText: 'How long you take to pay bills',
    },
  ],
  clientScript: 'cash-flow-forecast',
  analysisType: 'cash-flow-forecast',
};
