import type { CalculatorConfig } from '../../types';

export const credit_riskCalculator: CalculatorConfig = {
  id: 'credit-risk',
  title: 'Credit Risk Analysis',
  description:
    'Credit risk analysis with Probability of Default (PD), Loss Given Default (LGD), and Expected Loss',
  category: 'business',
  icon: '⚠️',
  color: 'red',
  keywords: ['credit risk', 'pd', 'lgd', 'expected loss', 'default'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is Probability of Default (PD)?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: "Probability of Default (PD) is the likelihood that a borrower will default on their debt obligations within a specific time period. It's a key component of credit risk assessment.",
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Credit Risk Analysis', href: '/calculator/credit-risk' },
  ],
  formFields: [
    {
      id: 'annualRevenue',
      name: 'annualRevenue',
      type: 'number',
      label: 'Annual Revenue ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Financials',
    },
    {
      id: 'ebitda',
      name: 'ebitda',
      type: 'number',
      label: 'EBITDA ($)',
      required: true,
      group: 'Financials',
    },
    {
      id: 'netIncome',
      name: 'netIncome',
      type: 'number',
      label: 'Net Income ($)',
      required: true,
      group: 'Financials',
    },
    {
      id: 'totalDebt',
      name: 'totalDebt',
      type: 'number',
      label: 'Total Debt ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Financials',
    },
    {
      id: 'totalAssets',
      name: 'totalAssets',
      type: 'number',
      label: 'Total Assets ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Financials',
    },
    {
      id: 'exposureAtDefault',
      name: 'exposureAtDefault',
      type: 'number',
      label: 'Exposure at Default (EAD) ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Debt Info',
    },
    {
      id: 'recoveryRate',
      name: 'recoveryRate',
      type: 'number',
      label: 'Recovery Rate (%)',
      min: 0,
      max: 100,
      step: 0.01,
      required: true,
      group: 'Debt Info',
    },
  ],
  clientScript: 'credit-risk',
  analysisType: 'credit-risk',
};
