import type { CalculatorConfig } from '../../types';

export const dcf_valuationCalculator: CalculatorConfig = {
  id: 'dcf-valuation',
  title: 'DCF Valuation Calculator',
  description:
    'Detailed discounted cash flow analysis with sensitivity analysis and scenario modeling for accurate business valuation',
  category: 'business',
  icon: '📊',
  color: 'blue',
  keywords: [
    'dcf',
    'valuation',
    'discounted cash flow',
    'business valuation',
    'investment analysis',
  ],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is DCF valuation?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'DCF (Discounted Cash Flow) valuation estimates the intrinsic value of a business by projecting future cash flows and discounting them back to present value using an appropriate discount rate.',
        },
      },
      {
        '@type': 'Question',
        name: 'How do I determine the discount rate for DCF?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: "The discount rate is typically the company's weighted average cost of capital (WACC), which reflects the cost of both debt and equity financing. It should account for the risk profile of the business.",
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Models', href: '/models' },
    { name: 'DCF Valuation', href: '/dcf-valuation' },
  ],
  formFields: [
    {
      id: 'revenue',
      name: 'revenue',
      type: 'number',
      label: 'Current Revenue ($)',
      min: 0,
      step: 1000,
      required: true,
    },
    {
      id: 'revenueGrowth',
      name: 'revenueGrowth',
      type: 'number',
      label: 'Revenue Growth Rate (%)',
      min: 0,
      max: 100,
      step: 0.1,
      required: true,
    },
    {
      id: 'ebitdaMargin',
      name: 'ebitdaMargin',
      type: 'number',
      label: 'EBITDA Margin (%)',
      min: 0,
      max: 100,
      step: 0.1,
      required: true,
    },
    {
      id: 'taxRate',
      name: 'taxRate',
      type: 'number',
      label: 'Tax Rate (%)',
      min: 0,
      max: 100,
      step: 0.1,
      required: true,
    },
    {
      id: 'capex',
      name: 'capex',
      type: 'number',
      label: 'Annual CapEx ($)',
      min: 0,
      step: 1000,
      required: true,
    },
    {
      id: 'workingCapitalChange',
      name: 'workingCapitalChange',
      type: 'number',
      label: 'Working Capital Change ($)',
      step: 1000,
      required: true,
    },
    {
      id: 'terminalGrowthRate',
      name: 'terminalGrowthRate',
      type: 'number',
      label: 'Terminal Growth Rate (%)',
      min: 0,
      max: 10,
      step: 0.1,
      required: true,
    },
    {
      id: 'discountRate',
      name: 'discountRate',
      type: 'number',
      label: 'Discount Rate (%)',
      min: 0,
      max: 50,
      step: 0.1,
      required: true,
    },
    {
      id: 'projectionYears',
      name: 'projectionYears',
      type: 'number',
      label: 'Projection Years',
      min: 3,
      max: 20,
      required: true,
    },
    {
      id: 'sharesOutstanding',
      name: 'sharesOutstanding',
      type: 'number',
      label: 'Shares Outstanding',
      min: 0,
      step: 1000,
      required: true,
    },
  ],
  clientScript: 'dcf-valuation',
  analysisType: 'dcf-valuation',
};
