import type { CalculatorConfig } from '../../types';

export const lboCalculator: CalculatorConfig = {
  id: 'lbo',
  title: 'LBO Model',
  description: 'Leveraged buyout analysis with IRR, MOIC, debt paydown, and exit scenarios',
  category: 'business',
  icon: '📈',
  color: 'purple',
  keywords: ['lbo', 'leveraged buyout', 'private equity', 'irr', 'moic'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is an LBO?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'A Leveraged Buyout (LBO) is a transaction where a company is acquired using a significant amount of borrowed money. The assets of the company being acquired are often used as collateral for the loans.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'LBO Model', href: '/calculator/lbo' },
  ],
  formFields: [
    {
      id: 'ebitda',
      name: 'ebitda',
      type: 'number',
      label: 'EBITDA ($)',
      min: 0,
      step: 100000,
      required: true,
      group: 'Target Company',
    },
    {
      id: 'revenue',
      name: 'revenue',
      type: 'number',
      label: 'Revenue ($)',
      min: 0,
      step: 100000,
      required: true,
      group: 'Target Company',
    },
    {
      id: 'purchasePrice',
      name: 'purchasePrice',
      type: 'number',
      label: 'Purchase Price ($)',
      min: 0,
      step: 100000,
      required: true,
      group: 'Transaction',
    },
    {
      id: 'equityContribution',
      name: 'equityContribution',
      type: 'number',
      label: 'Equity Contribution ($)',
      min: 0,
      step: 100000,
      required: true,
      group: 'Transaction',
    },
    {
      id: 'debtAmount',
      name: 'debtAmount',
      type: 'number',
      label: 'Debt Amount ($)',
      min: 0,
      step: 100000,
      required: true,
      group: 'Transaction',
    },
    {
      id: 'seniorDebtAmount',
      name: 'seniorDebtAmount',
      type: 'number',
      label: 'Senior Debt Amount ($)',
      min: 0,
      step: 100000,
      required: true,
      group: 'Financing',
    },
    {
      id: 'seniorDebtRate',
      name: 'seniorDebtRate',
      type: 'number',
      label: 'Senior Debt Rate (%)',
      min: 0,
      max: 20,
      step: 0.01,
      required: true,
      group: 'Financing',
    },
    {
      id: 'exitMultiple',
      name: 'exitMultiple',
      type: 'number',
      label: 'Exit Multiple',
      min: 3,
      max: 20,
      step: 0.1,
      required: true,
      group: 'Projections',
    },
    {
      id: 'holdingPeriod',
      name: 'holdingPeriod',
      type: 'number',
      label: 'Holding Period (years)',
      min: 3,
      max: 10,
      required: true,
      group: 'Projections',
    },
  ],
  clientScript: 'lbo',
  analysisType: 'lbo',
};
