import type { CalculatorConfig } from '../../types';

export const ma_analysisCalculator: CalculatorConfig = {
  id: 'ma-analysis',
  title: 'M&A Analysis Calculator',
  description:
    'Comprehensive merger and acquisition analysis including valuation, synergy assessment, and integration planning',
  category: 'business',
  icon: '🤝',
  color: 'purple',
  keywords: ['m&a', 'merger', 'acquisition', 'synergy', 'accretion', 'dilution'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is accretion/dilution analysis?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: "Accretion/dilution analysis determines whether a merger or acquisition will increase (accretion) or decrease (dilution) the acquiring company's earnings per share after the transaction.",
        },
      },
      {
        '@type': 'Question',
        name: 'How do you calculate synergies in M&A?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Synergies are calculated by identifying cost savings (reduced overhead, economies of scale) and revenue enhancements (cross-selling, market expansion) that result from combining the two companies.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Models', href: '/models' },
    { name: 'M&A Analysis', href: '/calculator/ma-analysis' },
  ],
  formFields: [
    {
      id: 'transactionType',
      name: 'transactionType',
      type: 'select',
      label: 'Transaction Type',
      required: true,
      group: 'Transaction',
      options: [
        { value: 'acquisition', label: 'Acquisition' },
        { value: 'merger', label: 'Merger' },
        { value: 'divestiture', label: 'Divestiture' },
        { value: 'spin-off', label: 'Spin-Off' },
        { value: 'joint-venture', label: 'Joint Venture' },
      ],
    },
    {
      id: 'transactionStructure',
      name: 'transactionStructure',
      type: 'select',
      label: 'Transaction Structure',
      required: true,
      group: 'Transaction',
      options: [
        { value: 'cash', label: 'All-Cash' },
        { value: 'stock', label: 'All-Stock' },
        { value: 'mixed', label: 'Mixed (Cash + Stock)' },
        { value: 'asset-purchase', label: 'Asset Purchase' },
        { value: 'stock-purchase', label: 'Stock Purchase' },
      ],
    },
    {
      id: 'announcementDate',
      name: 'announcementDate',
      type: 'text',
      label: 'Announcement Date (YYYY-MM-DD)',
      placeholder: '2025-01-01',
      group: 'Transaction (Advanced)',
      advancedOnly: true,
      helpText: 'If blank, today is used',
    },
    {
      id: 'expectedClosingDate',
      name: 'expectedClosingDate',
      type: 'text',
      label: 'Expected Closing Date (YYYY-MM-DD)',
      placeholder: '2025-04-01',
      group: 'Transaction (Advanced)',
      advancedOnly: true,
      helpText: 'If blank, +90 days is used',
    },
    {
      id: 'transactionStatus',
      name: 'transactionStatus',
      type: 'select',
      label: 'Transaction Status',
      group: 'Transaction (Advanced)',
      advancedOnly: true,
      options: [
        { value: 'announced', label: 'Announced' },
        { value: 'pending', label: 'Pending' },
        { value: 'completed', label: 'Completed' },
        { value: 'terminated', label: 'Terminated' },
      ],
    },

    {
      id: 'acquirerName',
      name: 'acquirerName',
      type: 'text',
      label: 'Acquirer Name',
      placeholder: 'Acquirer Inc.',
      required: true,
      group: 'Acquirer',
    },
    {
      id: 'acquirerTicker',
      name: 'acquirerTicker',
      type: 'text',
      label: 'Acquirer Ticker',
      placeholder: 'ACQ',
      group: 'Acquirer (Advanced)',
      advancedOnly: true,
    },
    {
      id: 'acquirerSharesOutstanding',
      name: 'acquirerSharesOutstanding',
      type: 'number',
      label: 'Acquirer Shares Outstanding',
      min: 0,
      step: 1000,
      required: true,
      group: 'Acquirer',
    },
    {
      id: 'acquirerCurrentPrice',
      name: 'acquirerCurrentPrice',
      type: 'number',
      label: 'Acquirer Current Share Price ($)',
      min: 0,
      step: 0.01,
      required: true,
      group: 'Acquirer',
    },
    {
      id: 'acquirerRevenue',
      name: 'acquirerRevenue',
      type: 'number',
      label: 'Acquirer Revenue ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Acquirer',
    },
    {
      id: 'acquirerEbitda',
      name: 'acquirerEbitda',
      type: 'number',
      label: 'Acquirer EBITDA ($)',
      step: 1000,
      required: true,
      group: 'Acquirer',
    },
    {
      id: 'acquirerNetIncome',
      name: 'acquirerNetIncome',
      type: 'number',
      label: 'Acquirer Net Income ($)',
      step: 1000,
      required: true,
      group: 'Acquirer',
    },
    {
      id: 'acquirerTotalDebt',
      name: 'acquirerTotalDebt',
      type: 'number',
      label: 'Acquirer Total Debt ($)',
      min: 0,
      step: 1000,
      group: 'Acquirer (Advanced)',
      advancedOnly: true,
      helpText: 'If blank, 0 is used',
    },
    {
      id: 'acquirerCashAndEquivalents',
      name: 'acquirerCashAndEquivalents',
      type: 'number',
      label: 'Acquirer Cash & Equivalents ($)',
      min: 0,
      step: 1000,
      group: 'Acquirer (Advanced)',
      advancedOnly: true,
      helpText: 'If blank, 0 is used',
    },
    {
      id: 'acquirerBeta',
      name: 'acquirerBeta',
      type: 'number',
      label: 'Acquirer Beta',
      min: 0,
      max: 3,
      step: 0.01,
      group: 'Acquirer (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 1.0',
    },
    {
      id: 'acquirerCreditRating',
      name: 'acquirerCreditRating',
      type: 'text',
      label: 'Acquirer Credit Rating',
      placeholder: 'BBB+',
      group: 'Acquirer (Advanced)',
      advancedOnly: true,
    },

    {
      id: 'targetName',
      name: 'targetName',
      type: 'text',
      label: 'Target Name',
      placeholder: 'Target Corp.',
      required: true,
      group: 'Target',
    },
    {
      id: 'targetTicker',
      name: 'targetTicker',
      type: 'text',
      label: 'Target Ticker',
      placeholder: 'TGT',
      group: 'Target (Advanced)',
      advancedOnly: true,
    },
    {
      id: 'targetSharesOutstanding',
      name: 'targetSharesOutstanding',
      type: 'number',
      label: 'Target Shares Outstanding',
      min: 0,
      step: 1000,
      required: true,
      group: 'Target',
    },
    {
      id: 'targetCurrentPrice',
      name: 'targetCurrentPrice',
      type: 'number',
      label: 'Target Current Share Price ($)',
      min: 0,
      step: 0.01,
      required: true,
      group: 'Target',
    },
    {
      id: 'targetRevenue',
      name: 'targetRevenue',
      type: 'number',
      label: 'Target Revenue ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Target',
    },
    {
      id: 'targetEbitda',
      name: 'targetEbitda',
      type: 'number',
      label: 'Target EBITDA ($)',
      step: 1000,
      required: true,
      group: 'Target',
    },
    {
      id: 'targetNetIncome',
      name: 'targetNetIncome',
      type: 'number',
      label: 'Target Net Income ($)',
      step: 1000,
      required: true,
      group: 'Target',
    },
    {
      id: 'targetTotalDebt',
      name: 'targetTotalDebt',
      type: 'number',
      label: 'Target Total Debt ($)',
      min: 0,
      step: 1000,
      group: 'Target (Advanced)',
      advancedOnly: true,
      helpText: 'If blank, 0 is used',
    },
    {
      id: 'targetCashAndEquivalents',
      name: 'targetCashAndEquivalents',
      type: 'number',
      label: 'Target Cash & Equivalents ($)',
      min: 0,
      step: 1000,
      group: 'Target (Advanced)',
      advancedOnly: true,
      helpText: 'If blank, 0 is used',
    },
    {
      id: 'targetBeta',
      name: 'targetBeta',
      type: 'number',
      label: 'Target Beta',
      min: 0,
      max: 3,
      step: 0.01,
      group: 'Target (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 1.0',
    },
    {
      id: 'targetCreditRating',
      name: 'targetCreditRating',
      type: 'text',
      label: 'Target Credit Rating',
      placeholder: 'BB',
      group: 'Target (Advanced)',
      advancedOnly: true,
    },

    {
      id: 'purchasePrice',
      name: 'purchasePrice',
      type: 'number',
      label: 'Purchase Price ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Deal Terms',
    },
    {
      id: 'cashPercentage',
      name: 'cashPercentage',
      type: 'number',
      label: 'Cash Consideration (%)',
      min: 0,
      max: 100,
      step: 1,
      required: true,
      group: 'Deal Terms',
    },
    {
      id: 'exchangeRatio',
      name: 'exchangeRatio',
      type: 'number',
      label: 'Exchange Ratio (optional)',
      min: 0,
      step: 0.0001,
      group: 'Deal Terms (Advanced)',
      advancedOnly: true,
      helpText: 'Acquirer shares per target share (for stock or mixed deals)',
    },
    {
      id: 'premiumPercent',
      name: 'premiumPercent',
      type: 'number',
      label: 'Offer Premium (%) (optional)',
      min: 0,
      max: 200,
      step: 0.1,
      group: 'Deal Terms (Advanced)',
      advancedOnly: true,
      helpText: 'If blank, premium is derived from purchase price vs target market cap',
    },

    {
      id: 'financingNewDebt',
      name: 'financingNewDebt',
      type: 'number',
      label: 'New Debt Financing ($)',
      min: 0,
      step: 1000,
      group: 'Financing (Optional)',
      advancedOnly: true,
      helpText: 'If blank, 0 is used',
    },
    {
      id: 'financingCashOnHand',
      name: 'financingCashOnHand',
      type: 'number',
      label: 'Cash on Hand Used ($)',
      min: 0,
      step: 1000,
      group: 'Financing (Optional)',
      advancedOnly: true,
      helpText: 'If blank, 0 is used',
    },
    {
      id: 'financingEquityIssuance',
      name: 'financingEquityIssuance',
      type: 'number',
      label: 'Equity Issuance ($)',
      min: 0,
      step: 1000,
      group: 'Financing (Optional)',
      advancedOnly: true,
      helpText: 'If blank, 0 is used',
    },
    {
      id: 'financingOtherSources',
      name: 'financingOtherSources',
      type: 'number',
      label: 'Other Sources ($)',
      min: 0,
      step: 1000,
      group: 'Financing (Optional)',
      advancedOnly: true,
      helpText: 'If blank, 0 is used',
    },

    {
      id: 'annualCostSynergies',
      name: 'annualCostSynergies',
      type: 'number',
      label: 'Annual Cost Synergies ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Synergies',
    },
    {
      id: 'annualRevenueSynergies',
      name: 'annualRevenueSynergies',
      type: 'number',
      label: 'Annual Revenue Synergies ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Synergies',
    },
    {
      id: 'annualTaxSynergies',
      name: 'annualTaxSynergies',
      type: 'number',
      label: 'Annual Tax Synergies ($) (optional)',
      min: 0,
      step: 1000,
      group: 'Synergies (Advanced)',
      advancedOnly: true,
      helpText: 'If blank, 0 is used',
    },
    {
      id: 'costSynergyRealizationPeriod',
      name: 'costSynergyRealizationPeriod',
      type: 'number',
      label: 'Cost Synergy Realization (years)',
      min: 1,
      max: 5,
      step: 1,
      group: 'Synergies (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 3',
    },
    {
      id: 'costSynergyProbability',
      name: 'costSynergyProbability',
      type: 'number',
      label: 'Cost Synergy Probability (0-1)',
      min: 0,
      max: 1,
      step: 0.01,
      group: 'Synergies (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 0.8',
    },
    {
      id: 'costSynergyCategories',
      name: 'costSynergyCategories',
      type: 'text',
      label: 'Cost Synergy Categories (optional)',
      placeholder: 'Headcount:10000000@2; Procurement:5000000@1',
      group: 'Synergies (Advanced)',
      advancedOnly: true,
      helpText: 'Format: Name:Amount@TimingYears; ...',
    },
    {
      id: 'revenueSynergyRealizationPeriod',
      name: 'revenueSynergyRealizationPeriod',
      type: 'number',
      label: 'Revenue Synergy Realization (years)',
      min: 1,
      max: 5,
      step: 1,
      group: 'Synergies (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 3',
    },
    {
      id: 'revenueSynergyProbability',
      name: 'revenueSynergyProbability',
      type: 'number',
      label: 'Revenue Synergy Probability (0-1)',
      min: 0,
      max: 1,
      step: 0.01,
      group: 'Synergies (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 0.6',
    },
    {
      id: 'revenueSynergyCategories',
      name: 'revenueSynergyCategories',
      type: 'text',
      label: 'Revenue Synergy Categories (optional)',
      placeholder: 'Cross-sell:8000000@3; Expansion:4000000@2',
      group: 'Synergies (Advanced)',
      advancedOnly: true,
      helpText: 'Format: Name:Amount@TimingYears; ...',
    },
    {
      id: 'taxSynergyRealizationPeriod',
      name: 'taxSynergyRealizationPeriod',
      type: 'number',
      label: 'Tax Synergy Realization (years)',
      min: 1,
      max: 5,
      step: 1,
      group: 'Synergies (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 2',
    },
    {
      id: 'taxSynergyProbability',
      name: 'taxSynergyProbability',
      type: 'number',
      label: 'Tax Synergy Probability (0-1)',
      min: 0,
      max: 1,
      step: 0.01,
      group: 'Synergies (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 0.7',
    },

    {
      id: 'integrationTimeline',
      name: 'integrationTimeline',
      type: 'number',
      label: 'Integration Timeline (years)',
      min: 1,
      max: 10,
      step: 1,
      group: 'Integration (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 2',
    },
    {
      id: 'integrationOneTimeCosts',
      name: 'integrationOneTimeCosts',
      type: 'number',
      label: 'Integration One-time Costs ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Integration',
    },
    {
      id: 'integrationAnnualCosts',
      name: 'integrationAnnualCosts',
      type: 'number',
      label: 'Integration Annual Costs ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Integration',
    },
    {
      id: 'integrationCostDuration',
      name: 'integrationCostDuration',
      type: 'number',
      label: 'Integration Cost Duration (years)',
      min: 1,
      max: 5,
      step: 1,
      group: 'Integration (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 2',
    },
    {
      id: 'integrationRisks',
      name: 'integrationRisks',
      type: 'text',
      label: 'Integration Risks (optional)',
      placeholder: 'IT|Systems integration|0.4|high|Dedicated integration PMO',
      group: 'Integration (Advanced)',
      advancedOnly: true,
      helpText:
        'One per line: Category|Description|Probability(0-1)|Impact(low/medium/high)|Mitigation',
    },

    {
      id: 'discountRatePercent',
      name: 'discountRatePercent',
      type: 'number',
      label: 'Discount Rate (%)',
      min: 0,
      max: 100,
      step: 0.1,
      group: 'Analysis Settings (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 10%',
    },
    {
      id: 'taxRatePercent',
      name: 'taxRatePercent',
      type: 'number',
      label: 'Tax Rate (%)',
      min: 0,
      max: 100,
      step: 0.1,
      group: 'Analysis Settings (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 25%',
    },
    {
      id: 'terminalGrowthRatePercent',
      name: 'terminalGrowthRatePercent',
      type: 'number',
      label: 'Terminal Growth Rate (%)',
      min: 0,
      max: 10,
      step: 0.1,
      group: 'Analysis Settings (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 2.5%',
    },
    {
      id: 'forecastPeriodYears',
      name: 'forecastPeriodYears',
      type: 'number',
      label: 'Forecast Period (years)',
      min: 3,
      max: 10,
      step: 1,
      group: 'Analysis Settings (Advanced)',
      advancedOnly: true,
      helpText: 'Optional; defaults to 5',
    },
  ],
  clientScript: 'ma-analysis',
  analysisType: 'ma-analysis',
};
