import type { CalculatorConfig } from '../../types';

export const pricing_strategyCalculator: CalculatorConfig = {
  id: 'pricing-strategy',
  title: 'Pricing Strategy Calculator',
  description:
    'Optimize your product pricing with cost-plus, value-based, and competitive strategies. Find the optimal price point for maximum profit.',
  category: 'business',
  icon: '💲',
  color: 'orange',
  keywords: [
    'pricing',
    'strategy',
    'cost-plus',
    'value-based',
    'pricing optimization',
    'profit margin',
    'elasticity',
  ],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is value-based pricing?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Value-based pricing sets price based on what customers are willing to pay for the value delivered, not your costs. Often captures 30-40% more profit than cost-plus.',
        },
      },
      {
        '@type': 'Question',
        name: 'How does price elasticity affect my business?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Price elasticity measures how demand changes when price changes. A 10% price increase with 1.0 elasticity means 10% fewer units sold. Understanding this prevents pricing mistakes.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Pricing Strategy', href: '/calculator/pricing-strategy' },
  ],
  formFields: [
    {
      id: 'costPerUnit',
      name: 'costPerUnit',
      type: 'number',
      label: 'Cost per Unit',
      placeholder: '25',
      min: 0,
      step: 0.01,
      required: true,
      helpText: 'Your total cost to produce one unit',
      assistantAliases: ['cost', 'cost per unit', 'unit cost'],
    },
    {
      id: 'targetMargin',
      name: 'targetMargin',
      type: 'number',
      label: 'Target Margin (%)',
      placeholder: '40',
      min: 0,
      max: 1000,
      step: 1,
      required: true,
      helpText: 'Desired profit margin for cost-plus pricing',
      assistantAliases: ['margin', 'target margin', 'profit margin'],
    },
    {
      id: 'marketPrice',
      name: 'marketPrice',
      type: 'number',
      label: 'Competitor Market Price',
      placeholder: '50',
      min: 0,
      step: 0.01,
      required: true,
      helpText: 'What competitors charge for similar products',
      assistantAliases: ['competitor price', 'market price', 'price'],
    },
    {
      id: 'valueToCustomer',
      name: 'valueToCustomer',
      type: 'number',
      label: 'Value to Customer',
      placeholder: '100',
      min: 0,
      step: 0.01,
      required: true,
      helpText: 'Economic value your product creates for customers',
      assistantAliases: ['value to customer', 'customer value'],
    },
    {
      id: 'unitsSoldMonthly',
      name: 'unitsSoldMonthly',
      type: 'number',
      label: 'Units Sold Monthly',
      placeholder: '500',
      min: 1,
      step: 1,
      required: true,
      helpText: 'Current or expected monthly sales volume',
      assistantAliases: ['units sold', 'units sold monthly', 'units', 'monthly volume'],
    },
    {
      id: 'priceElasticity',
      name: 'priceElasticity',
      type: 'number',
      label: 'Price Elasticity',
      placeholder: '1.0',
      min: 0,
      max: 10,
      step: 0.1,
      required: true,
      helpText: '% demand change per % price change (1.0 = elastic, 0.5 = inelastic)',
      assistantAliases: ['elasticity', 'price elasticity'],
    },
  ],
  clientScript: 'pricing-strategy',
  analysisType: 'pricing-strategy',
};
