import type { CalculatorConfig } from '../../types';

export const project_financeCalculator: CalculatorConfig = {
  id: 'project-finance',
  title: 'Project Finance Analyzer',
  description: 'Project finance analysis with NPV, IRR, payback period, and sensitivity analysis',
  category: 'business',
  icon: '📊',
  color: 'blue',
  keywords: ['project finance', 'npv', 'irr', 'payback', 'capital budgeting'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is NPV?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'NPV (Net Present Value) is the difference between the present value of cash inflows and outflows. A positive NPV indicates the project is expected to generate value.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Project Finance', href: '/calculator/project-finance' },
  ],
  formFields: [
    {
      id: 'projectName',
      name: 'projectName',
      type: 'text',
      label: 'Project Name',
      required: true,
      group: 'Project Info',
    },
    {
      id: 'projectType',
      name: 'projectType',
      type: 'select',
      label: 'Project Type',
      required: true,
      group: 'Project Info',
      options: [
        { value: 'infrastructure', label: 'Infrastructure' },
        { value: 'real-estate', label: 'Real Estate' },
        { value: 'energy', label: 'Energy' },
        { value: 'manufacturing', label: 'Manufacturing' },
        { value: 'technology', label: 'Technology' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      id: 'initialInvestment',
      name: 'initialInvestment',
      type: 'number',
      label: 'Initial Investment ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Cash Flows',
    },
    {
      id: 'cashFlowYears',
      name: 'cashFlowYears',
      type: 'number',
      label: 'Number of Years',
      min: 1,
      max: 50,
      required: true,
      group: 'Cash Flows',
    },
    {
      id: 'equityPercentage',
      name: 'equityPercentage',
      type: 'number',
      label: 'Equity Percentage (%)',
      min: 0,
      max: 100,
      required: true,
      group: 'Financing',
    },
    {
      id: 'costOfEquity',
      name: 'costOfEquity',
      type: 'number',
      label: 'Cost of Equity (%)',
      min: 0,
      max: 50,
      step: 0.01,
      required: true,
      group: 'Financing',
    },
    {
      id: 'costOfDebt',
      name: 'costOfDebt',
      type: 'number',
      label: 'Cost of Debt (%)',
      min: 0,
      max: 50,
      step: 0.01,
      required: true,
      group: 'Financing',
    },
  ],
  clientScript: 'project-finance',
  analysisType: 'project-finance',
};
