import type { CalculatorConfig } from '../../types';

export const real_estate_investmentCalculator: CalculatorConfig = {
  id: 'real-estate-investment',
  title: 'Real Estate Investment Analysis',
  description: 'Real estate investment analysis with cap rate, cash-on-cash return, and IRR',
  category: 'business',
  icon: '🏢',
  color: 'green',
  keywords: ['real estate', 'cap rate', 'cash on cash', 'irr', 'investment'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is cap rate?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Cap rate (capitalization rate) is the ratio of Net Operating Income (NOI) to property value. It indicates the expected return on a real estate investment, assuming it was purchased with cash.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Real Estate Investment', href: '/calculator/real-estate-investment' },
  ],
  formFields: [
    {
      id: 'purchasePrice',
      name: 'purchasePrice',
      type: 'number',
      label: 'Purchase Price ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Property Info',
    },
    {
      id: 'propertyType',
      name: 'propertyType',
      type: 'select',
      label: 'Property Type',
      required: true,
      group: 'Property Info',
      options: [
        { value: 'residential', label: 'Residential' },
        { value: 'commercial', label: 'Commercial' },
        { value: 'multifamily', label: 'Multifamily' },
        { value: 'industrial', label: 'Industrial' },
        { value: 'retail', label: 'Retail' },
        { value: 'office', label: 'Office' },
      ],
    },
    {
      id: 'downPayment',
      name: 'downPayment',
      type: 'number',
      label: 'Down Payment ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Financing',
    },
    {
      id: 'loanAmount',
      name: 'loanAmount',
      type: 'number',
      label: 'Loan Amount ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Financing',
    },
    {
      id: 'interestRate',
      name: 'interestRate',
      type: 'number',
      label: 'Interest Rate (%)',
      min: 0,
      max: 20,
      step: 0.01,
      required: true,
      group: 'Financing',
    },
    {
      id: 'monthlyRent',
      name: 'monthlyRent',
      type: 'number',
      label: 'Monthly Rent ($)',
      min: 0,
      step: 100,
      required: true,
      group: 'Income',
    },
    {
      id: 'propertyTaxes',
      name: 'propertyTaxes',
      type: 'number',
      label: 'Property Taxes ($/year)',
      min: 0,
      step: 100,
      required: true,
      group: 'Expenses',
    },
    {
      id: 'insurance',
      name: 'insurance',
      type: 'number',
      label: 'Insurance ($/year)',
      min: 0,
      step: 100,
      required: true,
      group: 'Expenses',
    },
  ],
  clientScript: 'real-estate-investment',
  analysisType: 'real-estate-investment',
};
