import type { CalculatorConfig } from '../../types';

export const risk_managementCalculator: CalculatorConfig = {
  id: 'risk-management',
  title: 'Risk Management Calculator',
  description:
    'Comprehensive risk analysis including Value at Risk (VaR), stress testing, and portfolio risk optimization',
  category: 'business',
  icon: '⚠️',
  color: 'red',
  keywords: ['risk management', 'var', 'value at risk', 'stress testing', 'portfolio risk'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is Value at Risk (VaR)?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'VaR is a statistical measure that estimates the maximum potential loss of a portfolio over a specific time period with a given confidence level. It helps quantify downside risk.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is stress testing in risk management?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Stress testing evaluates how a portfolio would perform under extreme market conditions or specific adverse scenarios, helping identify potential vulnerabilities.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Models', href: '/models' },
    { name: 'Risk Management', href: '/risk-management' },
  ],
  formFields: [
    {
      id: 'portfolioValue',
      name: 'portfolioValue',
      type: 'number',
      label: 'Portfolio Value ($)',
      min: 0,
      step: 1000,
      required: true,
    },
    {
      id: 'expectedReturn',
      name: 'expectedReturn',
      type: 'number',
      label: 'Expected Annual Return (%)',
      min: -100,
      max: 100,
      step: 0.1,
      required: true,
    },
    {
      id: 'volatility',
      name: 'volatility',
      type: 'number',
      label: 'Annual Volatility (%)',
      min: 0,
      max: 100,
      step: 0.1,
      required: true,
    },
    {
      id: 'confidenceLevel',
      name: 'confidenceLevel',
      type: 'number',
      label: 'Confidence Level (%)',
      min: 90,
      max: 99.9,
      step: 0.1,
      required: true,
    },
    {
      id: 'timeHorizon',
      name: 'timeHorizon',
      type: 'number',
      label: 'Time Horizon (days)',
      min: 1,
      max: 365,
      required: true,
    },
    {
      id: 'recessionScenario',
      name: 'recessionScenario',
      type: 'number',
      label: 'Recession Scenario (%)',
      min: -100,
      max: 0,
      step: 1,
      required: true,
    },
    {
      id: 'inflationScenario',
      name: 'inflationScenario',
      type: 'number',
      label: 'Inflation Scenario (%)',
      min: -100,
      max: 100,
      step: 1,
      required: true,
    },
    {
      id: 'marketCrashScenario',
      name: 'marketCrashScenario',
      type: 'number',
      label: 'Market Crash Scenario (%)',
      min: -100,
      max: 0,
      step: 1,
      required: true,
    },
  ],
  clientScript: 'risk-management',
  analysisType: 'risk-management',
};
