import type { CalculatorConfig } from '../../types';

export const saas_metricsCalculator: CalculatorConfig = {
  id: 'saas-metrics',
  title: 'SaaS Metrics Dashboard',
  description:
    'Track MRR, ARR, churn, CAC, LTV, LTV:CAC ratio, payback period, and Rule of 40 for your SaaS business',
  category: 'business',
  icon: '📈',
  color: 'indigo',
  keywords: ['SaaS', 'MRR', 'ARR', 'churn', 'CAC', 'LTV', 'metrics', 'Rule of 40', 'subscription'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is a good LTV:CAC ratio for SaaS?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'A healthy LTV:CAC ratio is 3:1 or higher. This means customer lifetime value is 3x the cost to acquire them. Below 3:1 suggests unit economics need improvement.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is the Rule of 40?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Rule of 40 states that growth rate + profit margin should equal 40% or more. It measures the balance between growth and profitability for SaaS companies.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'SaaS Metrics', href: '/calculator/saas-metrics' },
  ],
  formFields: [
    {
      id: 'activeCustomers',
      name: 'activeCustomers',
      type: 'number',
      label: 'Active Customers',
      placeholder: '150',
      min: 1,
      step: 1,
      required: true,
    },
    {
      id: 'averageMonthlyRevenue',
      name: 'averageMonthlyRevenue',
      type: 'number',
      label: 'Average Revenue per Customer',
      placeholder: '99',
      min: 0.01,
      step: 0.01,
      required: true,
      helpText: 'Monthly subscription price per customer',
    },
    {
      id: 'newCustomersLastMonth',
      name: 'newCustomersLastMonth',
      type: 'number',
      label: 'New Customers Last Month',
      placeholder: '20',
      min: 0,
      step: 1,
      required: true,
    },
    {
      id: 'churnedCustomersLastMonth',
      name: 'churnedCustomersLastMonth',
      type: 'number',
      label: 'Churned Customers Last Month',
      placeholder: '5',
      min: 0,
      step: 1,
      required: true,
    },
    {
      id: 'salesMarketingSpend',
      name: 'salesMarketingSpend',
      type: 'number',
      label: 'Sales & Marketing Spend (Last Month)',
      placeholder: '10000',
      min: 0,
      step: 100,
      required: true,
    },
    {
      id: 'averageCustomerLifetimeMonths',
      name: 'averageCustomerLifetimeMonths',
      type: 'number',
      label: 'Avg Customer Lifetime (Months)',
      placeholder: '24',
      min: 1,
      step: 1,
      required: true,
      helpText: 'How long customers stay on average',
    },
    {
      id: 'grossMargin',
      name: 'grossMargin',
      type: 'number',
      label: 'Gross Margin (%)',
      placeholder: '80',
      min: 0,
      max: 100,
      step: 1,
      required: true,
      helpText: 'Typical SaaS is 70-85%',
    },
    {
      id: 'revenueGrowthRate',
      name: 'revenueGrowthRate',
      type: 'number',
      label: 'Revenue Growth Rate (% Annual)',
      placeholder: '50',
      min: -100,
      max: 1000,
      step: 1,
      required: true,
    },
  ],
  clientScript: 'saas-metrics',
  analysisType: 'saas-metrics',
};
