import type { CalculatorConfig } from '../../types';

export const unit_economicsCalculator: CalculatorConfig = {
  id: 'unit-economics',
  title: 'Unit Economics Calculator',
  description:
    'Analyze customer-level profitability with CAC, LTV, payback period, and cohort projections',
  category: 'business',
  icon: '📐',
  color: 'emerald',
  keywords: ['unit economics', 'CAC', 'LTV', 'churn', 'SaaS', 'payback', 'cohort'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is a good LTV:CAC ratio?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'A healthy LTV:CAC ratio is 3:1 or higher, meaning lifetime value is at least three times customer acquisition cost.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Unit Economics', href: '/calculator/unit-economics' },
  ],
  formFields: [
    {
      id: 'monthlyMarketingSpend',
      name: 'monthlyMarketingSpend',
      type: 'number',
      label: 'Monthly Marketing Spend ($)',
      min: 0,
      step: 100,
      required: true,
    },
    {
      id: 'newCustomersPerMonth',
      name: 'newCustomersPerMonth',
      type: 'number',
      label: 'New Customers per Month',
      min: 1,
      step: 1,
      required: true,
    },
    {
      id: 'averageMonthlyRevenue',
      name: 'averageMonthlyRevenue',
      type: 'number',
      label: 'Average Monthly Revenue per Customer ($)',
      min: 0.01,
      step: 0.01,
      required: true,
    },
    {
      id: 'averageCustomerLifespanMonths',
      name: 'averageCustomerLifespanMonths',
      type: 'number',
      label: 'Average Customer Lifespan (Months)',
      min: 1,
      step: 1,
      required: true,
    },
    {
      id: 'costOfGoodsSoldPercent',
      name: 'costOfGoodsSoldPercent',
      type: 'number',
      label: 'COGS (%)',
      min: 0,
      max: 100,
      step: 0.1,
      required: true,
    },
    {
      id: 'variableServicingCostPerCustomer',
      name: 'variableServicingCostPerCustomer',
      type: 'number',
      label: 'Variable Servicing Cost per Customer ($)',
      min: 0,
      step: 0.01,
      required: true,
    },
    {
      id: 'monthlyChurnRate',
      name: 'monthlyChurnRate',
      type: 'number',
      label: 'Monthly Churn Rate (%)',
      min: 0,
      max: 100,
      step: 0.1,
      required: true,
    },
    {
      id: 'organicGrowthPercent',
      name: 'organicGrowthPercent',
      type: 'number',
      label: 'Organic Growth (%)',
      min: 0,
      max: 100,
      step: 0.1,
      required: false,
      group: 'Optional Assumptions',
    },
    {
      id: 'referralRate',
      name: 'referralRate',
      type: 'number',
      label: 'Referral Rate (%)',
      min: 0,
      max: 100,
      step: 0.1,
      required: false,
      group: 'Optional Assumptions',
    },
    {
      id: 'discountRate',
      name: 'discountRate',
      type: 'number',
      label: 'Discount Rate (%)',
      min: 0,
      max: 50,
      step: 0.1,
      required: false,
      group: 'Optional Assumptions',
    },
    {
      id: 'revenueGrowthRate',
      name: 'revenueGrowthRate',
      type: 'number',
      label: 'Revenue Growth Rate (%)',
      min: -100,
      max: 500,
      step: 0.1,
      required: false,
      group: 'Optional Assumptions',
    },
  ],
  clientScript: 'unit-economics',
  analysisType: 'unit-economics',
};
