import type { CalculatorConfig } from '../../types';

export const working_capitalCalculator: CalculatorConfig = {
  id: 'working-capital',
  title: 'Working Capital Optimizer',
  description: 'Working capital optimization with cash conversion cycle and liquidity analysis',
  category: 'business',
  icon: '💧',
  color: 'blue',
  keywords: ['working capital', 'cash conversion cycle', 'liquidity', 'dso', 'dpo'],
  faqSchema: {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is working capital?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Working capital is the difference between current assets and current liabilities. It represents the funds available for day-to-day operations.',
        },
      },
    ],
  },
  breadcrumbs: [
    { name: 'Home', href: '/' },
    { name: 'Business Tools', href: '/models/business' },
    { name: 'Working Capital Optimizer', href: '/calculator/working-capital' },
  ],
  formFields: [
    {
      id: 'annualRevenue',
      name: 'annualRevenue',
      type: 'number',
      label: 'Annual Revenue ($)',
      min: 0,
      step: 10000,
      required: true,
      group: 'Company Info',
    },
    {
      id: 'cash',
      name: 'cash',
      type: 'number',
      label: 'Cash ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Current Assets',
    },
    {
      id: 'accountsReceivable',
      name: 'accountsReceivable',
      type: 'number',
      label: 'Accounts Receivable ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Current Assets',
    },
    {
      id: 'inventory',
      name: 'inventory',
      type: 'number',
      label: 'Inventory ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Current Assets',
    },
    {
      id: 'accountsPayable',
      name: 'accountsPayable',
      type: 'number',
      label: 'Accounts Payable ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Current Liabilities',
    },
    {
      id: 'shortTermDebt',
      name: 'shortTermDebt',
      type: 'number',
      label: 'Short-Term Debt ($)',
      min: 0,
      step: 1000,
      required: true,
      group: 'Current Liabilities',
    },
  ],
  clientScript: 'working-capital',
  analysisType: 'working-capital',
};
