name = "financial-analysis-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# Bindings for local development
[[d1_databases]]
binding = "DB"
database_name = "financial-analysis-db"
database_id = "your_d1_database_id_here"

[[kv_namespaces]]
binding = "SESSIONS"
id = "your_kv_namespace_id_here"
preview_id = "your_kv_namespace_id_here"

[[r2_buckets]]
binding = "DOCUMENTS"
bucket_name = "financial-analysis-documents"
preview_bucket_name = "financial-analysis-documents"

# Development configuration
[dev]
port = 8787
local_protocol = "http"
upstream_protocol = "https"
host = "localhost"