/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: 00dc5dea9886c5999e080e1033d074c6)
interface __BaseEnv_Env {
	ENVIRONMENT?: "development" | "preview" | "production";
	WORKER_ROLE?: "mcp";
	MCP_DEV_AUTH_ENABLED?: "true";
	COMMIT_SHA?: "local" | "preview" | "production";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface DevelopmentEnv {
		ENVIRONMENT: "development";
		WORKER_ROLE: "mcp";
		MCP_DEV_AUTH_ENABLED: "true";
		COMMIT_SHA: "local";
	}
	interface PreviewEnv {
		ENVIRONMENT: "preview";
		WORKER_ROLE: "mcp";
		COMMIT_SHA: "preview";
	}
	interface ProductionEnv {
		ENVIRONMENT: "production";
		WORKER_ROLE: "mcp";
		COMMIT_SHA: "production";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "WORKER_ROLE" | "MCP_DEV_AUTH_ENABLED" | "COMMIT_SHA">> {}
}
