export interface JourneyModel {
  id: string;
  name: string;
  description: string;
  url: string;
  order: number;
  required: boolean;
}

export interface JourneyScenario {
  name: string;
  description: string;
  ageRange: string;
  complexity: string;
  duration: string;
  icon: string;
  color: string;
  models: JourneyModel[];
  workflow: string[];
}

export interface JourneyData {
  [scenarioId: string]: JourneyScenario;
}

export function getJourneyData(): JourneyData {
  return {
    'startup-planning': {
      name: 'Startup Financial Planning',
      description:
        'Complete financial planning journey for startups including initial capital investment, revenue projections, unit economics, cash flow, funding strategy, and growth planning',
      ageRange: 'Startup',
      complexity: 'Beginner',
      duration: '3-4 hours',
      icon: '🚀',
      color: 'blue',
      models: [
        {
          id: 'initial-capital-investment',
          name: 'Initial Capital Investment',
          description: 'Plan initial capital requirements and investment structure',
          url: '/journey/startup-planning/step/initial-capital-investment',
          order: 1,
          required: true,
        },
        {
          id: 'startup-budget',
          name: 'Startup Budget Planning',
          description: 'Create startup budget and cash flow projections',
          url: '/journey/startup-planning/step/startup-budget',
          order: 2,
          required: true,
        },
        {
          id: 'revenue-forecast',
          name: 'Revenue Projections',
          description: 'Project monthly revenue for the next 12-24 months',
          url: '/calculator/revenue-forecast',
          order: 3,
          required: true,
        },
        {
          id: 'unit-economics',
          name: 'Unit Economics Analysis',
          description: 'Validate business model with CAC, LTV, and payback analysis',
          url: '/calculator/unit-economics',
          order: 4,
          required: true,
        },
        {
          id: 'cash-flow-forecast',
          name: 'Cash Flow Planning',
          description: 'Project cash runway and working capital needs',
          url: '/calculator/cash-flow-forecast',
          order: 5,
          required: true,
        },
        {
          id: 'funding-strategy',
          name: 'Funding Strategy',
          description: 'Plan funding milestones and runway',
          url: '/journey/startup-planning/step/funding-strategy',
          order: 6,
          required: true,
        },
        {
          id: 'business-valuation',
          name: 'Business Valuation Tracking',
          description: 'Estimate current business value and track growth',
          url: '/calculator/business-valuation',
          order: 7,
          required: false,
        },
        {
          id: 'growth-planning',
          name: 'Growth Planning',
          description: 'Analyze growth scenarios and resource allocation',
          url: '/journey/startup-planning/step/growth-planning',
          order: 8,
          required: false,
        },
      ],
      workflow: [
        'Plan initial capital requirements and investment structure',
        'Create initial budget and cash flow projections',
        'Project revenue for next 12-24 months',
        'Validate unit economics (CAC, LTV, payback)',
        'Forecast cash flow and runway',
        'Plan funding milestones and strategy',
        'Track business valuation over time',
        'Analyze growth scenarios and optimize resources',
      ],
    },
    'ma-analysis-journey': {
      name: 'M&A Analysis Journey',
      description:
        'Complete M&A analysis journey including valuation, synergy analysis, and risk assessment',
      ageRange: 'Corporate',
      complexity: 'Advanced',
      duration: '4-6 hours',
      icon: '🏢',
      color: 'purple',
      models: [
        {
          id: 'acquisition-analysis',
          name: 'Acquisition Analysis',
          description: 'Complete M&A analysis with accretion/dilution',
          url: '/journey/ma-analysis-journey/step/acquisition-analysis',
          order: 1,
          required: true,
        },
        {
          id: 'target-valuation',
          name: 'Target Valuation',
          description: 'Detailed DCF analysis for target valuation',
          url: '/journey/ma-analysis-journey/step/target-valuation',
          order: 2,
          required: true,
        },
        {
          id: 'integration-planning',
          name: 'Integration Planning',
          description: 'Assess integration and operational risks',
          url: '/journey/ma-analysis-journey/step/integration-planning',
          order: 3,
          required: true,
        },
      ],
      workflow: [
        'Perform initial M&A analysis and accretion/dilution',
        'Conduct detailed DCF valuation of target',
        'Assess integration and operational risks',
        'Analyze synergy opportunities',
        'Create final acquisition recommendation',
      ],
    },
    'young-professional': {
      name: 'Young Professional Journey',
      description:
        'Complete financial planning journey for young professionals including debt management, budgeting, emergency fund, retirement planning, and wealth building',
      ageRange: '25-35',
      complexity: 'Beginner',
      duration: '2-3 hours',
      icon: '💼',
      color: 'green',
      models: [
        {
          id: 'financial-snapshot',
          name: 'Financial Snapshot',
          description: 'Assess your current financial situation and goals',
          url: '/journey/young-professional/step/financial-snapshot',
          order: 1,
          required: true,
        },
        {
          id: 'credit-card-payoff',
          name: 'Credit Card Payoff',
          description: 'Eliminate high-interest credit card debt',
          url: '/calculator/credit-card-payoff',
          order: 2,
          required: true,
        },
        {
          id: 'debt-strategy',
          name: 'Student Loan Strategy',
          description: 'Optimize student loan repayment and refinancing',
          url: '/journey/young-professional/step/debt-strategy',
          order: 3,
          required: true,
        },
        {
          id: 'emergency-fund',
          name: 'Emergency Fund',
          description: 'Build your financial safety net (3-6 months expenses)',
          url: '/journey/young-professional/step/emergency-fund',
          order: 4,
          required: true,
        },
        {
          id: 'retirement-start',
          name: 'Retirement Start',
          description: 'Begin building wealth for the future (401k, IRA)',
          url: '/journey/young-professional/step/retirement-start',
          order: 5,
          required: true,
        },
        {
          id: 'side-hustle',
          name: 'Side Hustle Income',
          description: 'Evaluate income-boosting opportunities',
          url: '/calculator/side-hustle-income',
          order: 6,
          required: false,
        },
        {
          id: 'goal-planning',
          name: 'Major Life Goals',
          description: 'Plan for home purchase, wedding, or other milestones',
          url: '/journey/young-professional/step/goal-planning',
          order: 7,
          required: false,
        },
      ],
      workflow: [
        'Assess your current financial situation',
        'Eliminate high-interest credit card debt',
        'Optimize student loan repayment strategy',
        'Build 3-6 month emergency fund',
        'Start retirement savings (401k, IRA)',
        'Explore side hustle income opportunities',
        'Plan for major life goals (home, wedding, etc.)',
      ],
    },
    'family-planning': {
      name: 'Family Planning Journey',
      description:
        'Complete financial planning journey for families including budgeting, savings, and retirement planning',
      ageRange: '30-45',
      complexity: 'Intermediate',
      duration: '3-4 hours',
      icon: '👨‍👩‍👧‍👦',
      color: 'orange',
      models: [
        {
          id: 'family-budget',
          name: 'Family Budget Planning',
          description: 'Create comprehensive family budget and expense tracking',
          url: '/journey/family-planning/step/family-budget',
          order: 1,
          required: true,
        },
        {
          id: 'family-savings',
          name: 'Family Savings Strategy',
          description: 'Plan for family financial goals and emergency fund',
          url: '/journey/family-planning/step/family-savings',
          order: 2,
          required: true,
        },
        {
          id: 'family-retirement',
          name: 'Family Retirement Planning',
          description: 'Plan for retirement with family considerations',
          url: '/journey/family-planning/step/family-retirement',
          order: 3,
          required: true,
        },
      ],
      workflow: [
        'Create comprehensive family budget and expense tracking',
        'Plan for family financial goals and emergency fund',
        'Plan for retirement with family considerations',
        'Monitor progress and adjust family financial strategy',
      ],
    },
    'home-buying': {
      name: 'Home Buying Journey',
      description:
        'Complete financial planning journey for purchasing a home including affordability analysis, mortgage planning, and down payment savings',
      ageRange: '25-40',
      complexity: 'Intermediate',
      duration: '2-3 hours',
      icon: '🏠',
      color: 'blue',
      models: [
        {
          id: 'financial-snapshot',
          name: 'Financial Snapshot',
          description: 'Assess your current financial situation',
          url: '/journey/home-buying/step/financial-snapshot',
          order: 1,
          required: true,
        },
        {
          id: 'goal-planning',
          name: 'What Can You Afford?',
          description: 'Analyze mortgage options and determine affordability',
          url: '/journey/home-buying/step/goal-planning',
          order: 2,
          required: true,
        },
        {
          id: 'retirement-start',
          name: 'Down Payment & Closing Costs',
          description: 'Calculate savings needed and timeline',
          url: '/journey/home-buying/step/retirement-start',
          order: 3,
          required: true,
        },
        {
          id: 'debt-strategy',
          name: 'Optimize Your Debt',
          description: 'Improve your debt-to-income ratio',
          url: '/journey/home-buying/step/debt-strategy',
          order: 4,
          required: true,
        },
        {
          id: 'emergency-fund',
          name: 'Build Home Ownership Buffer',
          description: 'Emergency fund for maintenance and repairs',
          url: '/journey/home-buying/step/emergency-fund',
          order: 5,
          required: true,
        },
      ],
      workflow: [
        'Assess your current financial situation',
        'Determine what price home you can afford',
        'Calculate down payment and closing costs needed',
        'Optimize your debt-to-income ratio',
        'Build emergency fund for home ownership',
      ],
    },
    'business-growth': {
      name: 'Business Growth Journey',
      description:
        'Comprehensive growth planning for small businesses covering financial health, unit economics, revenue forecasting, cash flow, pricing strategy, and business valuation.',
      ageRange: 'Business',
      complexity: 'Intermediate',
      duration: '2-3 hours',
      icon: '📊',
      color: 'indigo',
      models: [
        {
          id: 'ebitda-forecasting',
          name: 'Financial Health Check',
          description: 'Analyze current profitability and forecast EBITDA',
          url: '/ebitda-forecasting',
          order: 1,
          required: true,
        },
        {
          id: 'unit-economics',
          name: 'Unit Economics Analysis',
          description: 'Validate customer profitability with CAC, LTV, and payback',
          url: '/calculator/unit-economics',
          order: 2,
          required: true,
        },
        {
          id: 'revenue-forecast',
          name: 'Revenue Projections',
          description: 'Project revenue growth for next 12-24 months',
          url: '/calculator/revenue-forecast',
          order: 3,
          required: true,
        },
        {
          id: 'cash-flow-forecast',
          name: 'Cash Flow Planning',
          description: 'Ensure adequate cash runway and working capital',
          url: '/calculator/cash-flow-forecast',
          order: 4,
          required: true,
        },
        {
          id: 'pricing-strategy',
          name: 'Pricing Optimization',
          description: 'Optimize pricing for maximum profitability',
          url: '/calculator/pricing-strategy',
          order: 5,
          required: true,
        },
        {
          id: 'break-even',
          name: 'Break-Even Analysis',
          description: 'Calculate units needed for profitability',
          url: '/calculator/break-even',
          order: 6,
          required: true,
        },
        {
          id: 'business-valuation',
          name: 'Business Valuation',
          description: 'Track your business value and growth over time',
          url: '/calculator/business-valuation',
          order: 7,
          required: false,
        },
      ],
      workflow: [
        'Assess current financial health and profitability',
        'Validate unit economics and customer profitability',
        'Project revenue growth for planning and goals',
        'Plan cash flow to ensure adequate runway',
        'Optimize pricing strategy for maximum margins',
        'Calculate break-even point and targets',
        'Track business valuation and value drivers',
      ],
    },
    'debt-freedom': {
      name: 'Debt Freedom Journey',
      description:
        'Complete debt elimination journey with strategies for credit cards, student loans, auto loans, and other debts. Create your path to financial freedom.',
      ageRange: '25-45',
      complexity: 'Beginner',
      duration: '1-2 hours',
      icon: '💳',
      color: 'red',
      models: [
        {
          id: 'debt-assessment',
          name: 'Total Debt Assessment',
          description: 'Calculate total debt and create payoff timeline',
          url: '/calculator/debt-payoff',
          order: 1,
          required: true,
        },
        {
          id: 'credit-card-strategy',
          name: 'Credit Card Payoff Strategy',
          description: 'Eliminate high-interest credit card debt fast',
          url: '/calculator/credit-card-payoff',
          order: 2,
          required: true,
        },
        {
          id: 'student-loan-optimization',
          name: 'Student Loan Optimization',
          description: 'Compare repayment plans and refinancing options',
          url: '/calculator/student-loans',
          order: 3,
          required: true,
        },
        {
          id: 'budget-optimization',
          name: 'Budget Optimization',
          description: 'Free up cash to accelerate debt payoff',
          url: '/calculator/budget',
          order: 4,
          required: true,
        },
        {
          id: 'invest-vs-payoff',
          name: 'Invest vs Pay Off Debt',
          description: 'Decide when to invest vs pay down debt',
          url: '/calculator/invest-vs-payoff-debt',
          order: 5,
          required: false,
        },
      ],
      workflow: [
        'Assess total debt across all sources',
        'Create credit card payoff strategy (highest interest first)',
        'Optimize student loan repayment plan',
        'Optimize budget to maximize debt payments',
        'Decide optimal balance between investing and debt payoff',
        'Track progress and celebrate milestones',
      ],
    },
    'investment-analysis-journey': {
      name: 'Investment Analysis Journey',
      description:
        'Complete investment analysis journey including DCF valuation, comparable analysis, risk assessment, and portfolio optimization',
      ageRange: 'Corporate',
      complexity: 'Intermediate',
      duration: '3-4 hours',
      icon: '📊',
      color: 'blue',
      models: [
        {
          id: 'dcf-valuation',
          name: 'DCF Valuation',
          description: 'Detailed discounted cash flow analysis',
          url: '/calculator/dcf-valuation',
          order: 1,
          required: true,
        },
        {
          id: 'risk-management',
          name: 'Risk Assessment',
          description: 'Comprehensive risk analysis and portfolio optimization',
          url: '/calculator/risk-management',
          order: 2,
          required: true,
        },
        {
          id: 'ma-analysis',
          name: 'Comparable Analysis',
          description: 'M&A analysis for comparable company valuation',
          url: '/calculator/ma-analysis',
          order: 3,
          required: true,
        },
      ],
      workflow: [
        'Perform DCF valuation analysis',
        'Conduct comprehensive risk assessment',
        'Analyze comparable companies and transactions',
        'Optimize portfolio allocation',
        'Generate final investment recommendation',
      ],
    },
    'invest-vs-payoff-debt': {
      name: 'Invest vs Pay Off Debt Journey',
      description:
        'Complete decision-making journey to determine whether to invest extra money or pay off debt, considering emergency funds, interest rates, investment returns, and personal financial goals',
      ageRange: 'All Ages',
      complexity: 'Beginner',
      duration: '30-45 minutes',
      icon: '⚖️',
      color: 'purple',
      models: [
        {
          id: 'financial-foundation',
          name: 'Assess Financial Foundation',
          description: 'Check emergency fund status and current financial situation',
          url: '/journey/invest-vs-payoff-debt/step/financial-foundation',
          order: 1,
          required: true,
        },
        {
          id: 'understand-debt',
          name: 'Understand Your Debt',
          description: 'Document all debts, interest rates, and minimum payments',
          url: '/journey/invest-vs-payoff-debt/step/understand-debt',
          order: 2,
          required: true,
        },
        {
          id: 'evaluate-investments',
          name: 'Evaluate Investment Options',
          description: 'Assess expected returns, employer match, and investment opportunities',
          url: '/journey/invest-vs-payoff-debt/step/evaluate-investments',
          order: 3,
          required: true,
        },
        {
          id: 'compare-strategies',
          name: 'Compare Strategies',
          description: 'Run side-by-side comparison of pay debt vs invest vs hybrid strategies',
          url: '/journey/invest-vs-payoff-debt/step/compare-strategies',
          order: 4,
          required: true,
        },
        {
          id: 'make-decision',
          name: 'Make Your Decision',
          description: 'Get personalized recommendation based on your unique situation',
          url: '/journey/invest-vs-payoff-debt/step/make-decision',
          order: 5,
          required: true,
        },
      ],
      workflow: [
        'Assess emergency fund status and financial foundation',
        'Document all debts, interest rates, and minimum payments',
        'Evaluate investment options and expected returns',
        'Compare pay debt vs invest vs hybrid strategies',
        'Make informed decision based on personalized analysis',
      ],
    },
  };
}
